#
# include the standard macros
# 
include ../../../NCSNightlyBuild/makefile.inc

#
# Add additional source dirs
#
VPATH=../shared_src

#
# Link to these NCS libraries
#
NCS_LIBS= -lNCSEcw -lNCSCNet -lNCSUtil

#
# Name of this library (release target)
#
TARGET=	$(NCS_LIB_PATH)/libNCSEcwC

#
# Source files for this library
#
SRC=	compress.cpp

#
# include the lib make target macros
# 
include ../../../NCSNightlyBuild/makelibs.inc
