//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WallsMap.rc
//
#define IDS_NTI_FILES                   1
#define IDS_NTI_BROWSE                  2
#define IDS_ERR_DIRPROJECT              3
#define IDC_INSERTLINK                  3
#define IDOK2                           3
#define IDC_SELECTALL                   3
#define IDC_RELOAD                      3
#define IDC_IMAGEMODE                   3
#define IDCANCEL3                       3
#define IDC_CREATE_LOG                  3
#define IDS_ERR_FILE_RW                 4
#define IDCANCEL2                       4
#define IDC_REPLACEALL                  4
#define IDS_FILE_EXISTDLG               5
#define IDC_SAVE                        5
#define IDS_INSERT_FILELINK             6
#define IDS_SAVETOFILE                  7
#define IDP_AFXOLEINIT_FAILED           8
#define IDS_STRING9                     9
#define IDS_ABOUT_TITLE                 9
#define IDS_WEBMAP_INFO                 10
#define IDS_FMT_PLACEMARK               11
#define IDS_FMT_LOOKAT                  12
#define IDS_COMPARE_OPEN                13
#define IDS_COMPARE_FCN                 13
#define IDS_REPLWITHFILE                14
#define IDD_ABOUTBOX                    100
#define IDR_RTF_CONTEXT                 101
#define IDD_DBFGRID_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_ERR_FILERES                 105
#define IDS_ERR_OPENLAYER1              106
#define IDD_PAGE_DETAILS                107
#define IDS_NTL_FILES                   107
#define IDS_NTL_SAVEAS                  108
#define IDS_NTL_ASK_TO_SAVE             109
#define IDS_ERR_OPENSHAPE1              110
#define IDS_ERR_MAG_LOAD                111
#define IDS_ERR_OPENLSET1               112
#define IDS_ERR_OPENLAYER0              113
#define IDS_NTI_EXPAND                  114
#define IDS_ABORTEXPORT                 115
#define IDS_ABORTEXPAND                 116
#define IDS_NTI_TRUNCATE1               117
#define IDS_ERR_OPENSHPLAYER1           118
#define IDS_ERR_NTIEXPANDRO             119
#define IDBROWSE                        120
#define IDC_VERT_DLG                    120
#define IDC_HORIZ_DLG                   121
#define IDC_BROWSE_SHPDEF               121
#define ID_RELOCATE_SHAPE               122
#define IDS_ERR_LATITUDE                124
#define IDS_ERR_LONGITUDE               125
#define IDR_MAINFRAME                   128
#define IDR_WallsMapTYPE                129
#define IDB_CHECKBOXES                  129
#define IDD_COMM_SETTINGS               129
#define IDD_GPS_PORTSETTING             129
#define IDS_ERR_BADINT2                 130
#define IDD_COLUMNS                     130
#define IDS_MSG_SHOWCENTER              131
#define IDR_SORTMENU                    131
#define IDS_ERR_SIZEIMAGE2              132
#define IDS_ERR_SHOWCENTER              133
#define IDD_DBTEDITDLG                  134
#define IDC_CURSOR_ZOOMIN               135
#define IDS_MSG_CONFIRMDEL              135
#define IDC_CURSOR_ZOOMOUT              136
#define IDS_ERR_SHPREEDIT1              136
#define IDD_COMPARE_FCN                 136
#define IDC_CURSOR_HAND                 137
#define IDS_ERR_SHPNOEDIT1              137
#define IDD_EXPORT_NTI                  138
#define IDS_SHP_SAVEONDELETE            138
#define IDS_ERR_SHPREEDIT               139
#define IDD_PERCENT_ZOOM                140
#define IDS_MSG_SAVEATTR                140
#define IDR_LYR_CONTEXT                 141
#define IDD_SYMBOLS                     142
#define ID_EXPORT_SHAPES                144
#define ID_SET_EDITABLE                 145
#define IDS_MSG_CONFIRMUNDEL            146
#define IDS_SHP_FILES                   147
#define IDS_SHP_EXPORT                  148
#define IDS_PRJ_NAD83                   149
#define IDS_PRJ_NAD27                   150
#define IDS_PRJ_NAD83UTM                151
#define IDD_EXPAND_NTI                  152
#define IDS_PRJ_NAD27UTM                152
#define IDD_SYMBOLS_POLY                153
#define IDS_SHPDEF_FILES                153
#define IDD_EDITTITLE                   154
#define IDS_SHPDEF_OPEN                 154
#define IDS_JPG_FILES                   155
#define IDS_BMP_FILES                   156
#define IDS_PNG_FILES                   156
#define IDS_BMP_SAVEAS                  157
#define IDS_PNG_SAVEAS                  157
#define IDS_INSERT_LINK                 158
#define IDS_RTF_PASTE                   159
#define IDB_POLYLINE                    160
#define IDS_RTF_CONVERT2PLAIN           160
#define IDS_KML_FILES                   161
#define IDB_SCALEBAR                    162
#define IDS_KML_EXPORT                  162
#define IDD_BACKCOLOR                   163
#define IDS_RTF_FILES                   163
#define IDD_GEDEFAULTSDLG               164
#define IDS_ZIP_FILES                   164
#define IDS_ZIP_SAVEAS                  165
#define IDD_SHOW_SHAPE                  166
#define IDS_XLS_FILES                   166
#define IDD_MEMUSAGEDLG                 167
#define IDS_XLS_EXPORT                  167
#define IDR_SHOW_CONTEXT                168
#define IDS_GPS_SAVEAS                  168
#define IDC_CURSOR_SELECT               169
#define IDS_PRJ_WGS84GEO                169
#define IDS_PRJ_WGS84UTM                170
#define IDS_EXE_FILES                   171
#define IDS_TXTRTF_FILES                172
#define IDR_SHOWROOT_CONTEXT            173
#define IDC_CURSOR_SELECTADD            174
#define IDD_EXPORT_SHAPE                175
#define ID_LAUNCH_WEBMAP                179
#define IDR_FOLDER_CONTEXT              180
#define IDR_DATA2                       183
#define IDR_DATA3                       185
#define ID_DATA1                        185
#define IDR_DATA1                       190
#define IDD_IMAGE_VIEWER                191
#define IDR_IMAGE_CONTEXT               192
#define IDD_SELMARKER                   193
#define IDR_SCALE_CONTEXT               195
#define IDD_EDITOR_PREFS                202
#define IDC_MEASURE                     204
#define IDD_SCALERANGE                  204
#define IDD_OPTIONS_GE                  205
#define IDD_ADVANCED_SRCH               206
#define IDD_EXPORTIMG                   207
#define IDD_SELEDITED                   210
#define IDS_TXT_FILES                   211
#define IDD_UPDATED                     212
#define IDR_TABLE_CONTEXT               213
#define IDD_FINDDLGTBL                  214
#define IDR_FILL_CONTEXT                214
#define IDR_FILL_CONTEXT1               215
#define IDR_IMG_CONTEXT                 215
#define IDD_MSGCHECK                    216
#define IDD_EDITIMAGE                   217
#define IDB_DRAGINFO                    220
#define IDD_DIALOG1                     221
#define IDD_IMGZOOM                     221
#define IDB_CHECKBOX4                   221
#define IDD_LINKTEST                    223
#define IDC_BKGCOLOR                    224
#define IDD_MSGEXTENT                   224
#define IDD_RELOAD                      225
#define IDD_WEBMAP_FORMAT               228
#define IDD_SYMBOLS_IMG                 229
#define IDD_OPENEXISTING                230
#define IDD_PAGE_LAYERS                 231
#define IDD_ZIPDLG                      232
#define IDD_EXPORT_XLS                  233
#define IDD_CENTER_VIEW                 235
#define IDI_FOLDERCLOSE                 242
#define IDI_FOLDEROPEN                  243
#define IDB_BITMAP1                     244
#define IDB_FOLDERS_IMG                 244
#define IDB_BITMAP2                     245
#define IDB_WHITE                       245
#define IDR_MENU1                       249
#define IDR_MENU2                       250
#define IDD_COMPARESHP                  253
#define IDD_UPDZIP                      257
#define IDD_GPS_OPTIONS                 261
#define IDD_EXPORT_NTI_ADV2             263
#define IDD_DIALOG2                     266
#define IDD_FLDS_IGNORED                266
#define IDD_COPYSELECTED                268
#define IDD_TABLE_FILL                  269
#define IDD_TABLE_REPL                  273
#define IDC_PATHNAME                    377
#define IDC_PATH_SHPDEF                 378
#define IDC_RANGE                       378
#define IDC_WALLSURL                    509
#define IDC_WALLSMAPURL                 509
#define IDC_UPDATELINK                  509
#define IDC_NEWURL                      511
#define IDC_MCLEAR                      515
#define IDC_MOPAQUE                     516
#define IDC_MSIZE                       517
#define IDC_LSIZE                       518
#define IDC_MSIZE3                      519
#define IDC_MLINEW                      519
#define IDC_FGCOLOR                     521
#define IDC_COLORFRM                    522
#define IDC_LBLCOLOR                    523
#define IDC_LBLFONT                     524
#define IDC_BKGNDCOLOR                  525
#define IDC_MSHAPE                      528
#define IDC_LBLFIELD                    530
#define IDC_SPIN_MSIZE                  533
#define IDC_SPIN_MLINEW                 534
#define IDC_SPIN_LSIZE                  534
#define IDC_INC_HIDDEN                  566
#define IDC_INC_LINKED                  567
#define IDC_INC_LINKED2                 568
#define IDC_INC_SHAPEFILES              568
#define IDC_INC_SHAPEFILES2             569
#define IDC_INC_POINTS                  569
#define IDC_OPENEXISTING                653
#define IDC_ST_PATHNAME                 654
#define IDC_SAVEANDEXIT                 655
#define IDC_ST_TSSLINK                  1000
#define IDC_DBFLIST                     1000
#define IDC_EDIT1                       1001
#define IDC_TITLE                       1001
#define IDC_EDIT_EAST                   1001
#define IDC_STATIC_PLACEMENT            1001
#define IDC_LABELZOOM                   1001
#define IDC_LAYER_ZOOMOUT               1001
#define IDC_LOCAL_TIME                  1001
#define IDC_LISTCOLS                    1001
#define IDC_WEBMAP_FORMAT               1001
#define IDC_EDIT_SINGLE                 1001
#define IDC_MAX_CHARS                   1001
#define IDC_SHP_KEY                     1001
#define IDC_ARGUMENTS                   1001
#define IDC_FILLTEXT                    1001
#define IDC_FIND_WHAT                   1001
#define IDC_ADVANCED                    1002
#define IDC_EDIT_DETAILS                1002
#define IDC_EDIT_NORTH                  1002
#define IDC_LAYER_ZOOMIN                1002
#define IDC_UTC_TIME                    1002
#define IDC_CAPTION                     1002
#define IDC_EDIT_SINGLE2                1002
#define IDC_EDIT_MULTIPLE               1002
#define IDC_REPL_WITH                   1002
#define IDC_POINT_TREE                  1003
#define IDC_LABEL_ZOOMOUT               1003
#define IDC_DOT_CENTER                  1003
#define IDC_ST_PERCENT                  1004
#define IDC_FIELD_LIST                  1004
#define IDC_LABEL_ZOOMIN                1004
#define IDC_PROGRESS                    1005
#define IDC_LAYER_UP                    1005
#define IDC_APPLY                       1005
#define IDC_EXPORT                      1006
#define IDC_LAYER_ADD                   1006
#define IDC_RESTORE                     1006
#define IDC_SYMBOLOGY                   1007
#define IDC_SHOWMARKERS                 1007
#define IDC_UNDORELOCATE                1007
#define IDC_METHOD_LOCO                 1008
#define IDC_SHOWLABELS                  1008
#define IDC_SCALERANGE                  1008
#define IDC_METHOD_ZLIB                 1009
#define IDC_LAYER_DOWN                  1009
#define IDC_SELECTABLE                  1009
#define IDC_METHOD_JP2K                 1010
#define IDC_LAYER_DEL                   1010
#define IDC_SELECTABLE_SRCH             1010
#define IDC_OPACITY_SYM                 1010
#define IDC_RMG_G_BMG                   1011
#define IDC_LAYER_CONV                  1011
#define IDC_OPACITY_VEC                 1011
#define IDC_OPACITY_SYM2                1011
#define IDC_R_GMR_BMR                   1012
#define IDC_ATTRIBUTES                  1012
#define IDC_ST_OPACITY_SYM              1012
#define IDC_RMB_GMB_B                   1013
#define IDC_CHECK_SHOW_TOOLBAR          1013
#define IDC_ST_OPACITY_VEC              1013
#define IDC_NOFILTER                    1014
#define IDC_CHECK_SHOW_RULER            1014
#define IDC_REPLW_EXPORTED              1015
#define IDC_NO_OVERVIEWS                1015
#define IDC_DEFAULT                     1016
#define IDC_VIEW_EXPORTED2              1016
#define IDC_ADD_EXPORTED                1016
#define IDC_OVERWRITE                   1017
#define IDC_ST_STATS                    1018
#define IDC_ST_MESSAGE                  1018
#define IDC_METHOD_WEBP                 1018
#define IDC_ST_PROGRESS                 1019
#define IDC_PORT                        1019
#define IDC_METHOD_ZLIB2                1019
#define IDC_METHOD_LZMA                 1019
#define IDC_EXTENT_ENTIRE               1020
#define IDC_BKCOLOR                     1020
#define IDC_BAUD                        1020
#define IDC_EXTENT_WINDOW               1021
#define IDC_ST_NOTE                     1023
#define IDC_PERCENT                     1024
#define IDC_STATIC_SPLIT_PANE           1024
#define IDC_EXTENT_CUSTOM               1025
#define IDC_EDGE_LEFT                   1026
#define IDC_FINDBYLABEL                 1026
#define IDC_WIDTH                       1027
#define IDC_EDIT_LABEL                  1027
#define IDC_EDGE_TOP                    1028
#define IDC_HEIGHT                      1029
#define IDC_ST_NORTHING                 1029
#define IDC_ST_REGION                   1030
#define IDC_ST_EASTING                  1030
#define IDC_ST_ADVSETTINGS              1032
#define IDC_ENTERKEY                    1032
#define IDC_WEBP_PRESET                 1032
#define IDC_ST_FINDBYLABEL              1033
#define IDC_WEBP_QUALITY                1033
#define IDC_DBTEDIT                     1034
#define IDC_RESETATTR                   1035
#define IDC_RELOCATE                    1037
#define IDC_DATUM1                      1038
#define IDC_DATUM2                      1039
#define IDC_TYPEGEO                     1040
#define IDC_TYPEUTM                     1041
#define IDC_ST_DATUM                    1042
#define IDC_ST_TOTAL                    1043
#define IDC_ST_NOMATCHES                1044
#define IDC_INIT_EMPTY                  1045
#define IDC_RETAIN_DELETED              1046
#define IDC_COORD_SOURCE                1047
#define IDC_COORD_VIEW                  1048
#define IDC_ST_SOURCE                   1049
#define IDC_ST_SOURCE2                  1050
#define IDC_THUMB_LIST                  1050
#define IDC_EXCLUDE_MEMOS               1051
#define IDC_PREVIEW_PANE                1051
#define IDC_GEN_TEMPLATE                1052
#define IDC_ST_COUNTER                  1052
#define IDC_BUTTONLEFT                  1053
#define IDC_KBSIZE                      1053
#define IDC_ADD_LAYER                   1053
#define IDC_BUTTONRIGHT                 1054
#define IDC_MAKE_2D                     1054
#define IDC_LIST1                       1055
#define IDC_LIST2                       1056
#define IDC_MOVERIGHT                   1057
#define IDC_MOVELEFT                    1058
#define IDC_MOVEALL_RIGHT               1059
#define IDC_MARKSELECTED                1060
#define IDC_MOVEALL_LEFT                1060
#define IDC_FONT                        1061
#define IDC_LIST3                       1061
#define IDC_TEXTCOLOR                   1062
#define IDC_MOVERIGHT2                  1062
#define IDC_RTFEMPTY                    1063
#define IDC_LIST4                       1063
#define IDC_RTFTOOLBAR                  1064
#define IDC_TAB_TYPEMARK                1064
#define IDC_MOVELEFT2                   1064
#define IDC_MOVEALL_RIGHT2              1065
#define IDC_ST_ALLPOINTS                1066
#define IDC_MOVEALL_LEFT2               1066
#define IDC_ST_HIGHLIGHTED              1067
#define IDC_LABEL_SHOWALL               1068
#define IDC_ST_TRACKLINE                1068
#define IDC_LAYER_SHOWALL               1069
#define IDC_ST_CURRENTSCALE             1070
#define IDC_BROWSE                      1071
#define IDC_LAYER_NOSHOW                1072
#define IDC_DESCRIPTION                 1072
#define IDC_LABEL_NOSHOW                1073
#define IDC_DESC_INIT                   1076
#define IDC_ICONSIZE                    1077
#define IDC_DESC_FIELD                  1078
#define IDC_APPEND                      1079
#define IDC_REPLACE                     1080
#define IDC_SELMATCHED                  1080
#define IDC_SELUNMATCHED                1081
#define IDC_CLEAR                       1081
#define IDC_CLEAR_ALL                   1081
#define IDC_CLEAR_LAST                  1082
#define IDC_ADDMATCHED                  1082
#define IDC_ADDUNMATCHED                1083
#define IDC_KEEPMATCHED                 1084
#define IDC_KEEPUNMATCHED               1085
#define IDC_FIND_COMBO                  1086
#define IDC_SEL_MATCHCASE               1087
#define IDC_SEL_WHOLEWORDS              1088
#define IDC_SEL_VIEWONLY                1089
#define IDC_LOAD_DEFAULT                1090
#define IDC_SAVE_DEFAULT                1091
#define IDC_ST_FULLRES                  1092
#define IDC_BUTTON1                     1092
#define IDC_LOAD_DFLTS                  1092
#define IDC_RESETNAME                   1092
#define IDC_RESETROWS                   1092
#define IDC_MEMORY_USAGE                1092
#define IDC_PREV                        1092
#define IDC_MAX_OPACITY                 1092
#define IDC_RESET                       1092
#define IDC_ZOOM4X                      1092
#define IDC_TEST                        1092
#define IDC_RESTORE_DFLT                1092
#define IDC_SEL_IGNORED                 1092
#define IDC_TXTCOMP                     1092
#define IDC_SELECT_ALL                  1092
#define IDC_EDIT_SHP                    1093
#define IDC_ST_FULLRES2                 1093
#define IDC_NEXT                        1093
#define IDC_RESET2                      1093
#define IDC_EDIT_DBF                    1094
#define IDC_MEMORY_USAGE2               1094
#define IDC_EDIT_ADD                    1095
#define IDC_EDIT_DEL                    1096
#define IDC_VIEW_ONLY                   1097
#define IDC_ADDTOSEL                    1098
#define IDC_RECNO                       1098
#define IDC_EDIT_SOURCE                 1099
#define IDS_ADVSRCH_TITLE               1100
#define IDC_ST_DESC                     1100
#define IDC_NOPROMPT                    1101
#define IDC_USEFORALL                   1101
#define IDC_PRESERVE_NAME               1105
#define IDC_ST_SELCOUNT                 1106
#define IDC_LOOKIN                      1108
#define IDC_SEARCH_MEMOS                1109
#define IDC_ALLOW_EDITS                 1110
#define IDC_FILTER_RTF                  1110
#define IDC_SEARCH_RTF                  1110
#define IDC_ST_DRAGNOTE                 1111
#define IDC_USE_LAYOUT                  1112
#define IDC_CHK_NOTAGAIN                1113
#define IDC_ST_SIZE                     1123
#define IDC_ZOOMTOADDED                 1124
#define IDC_UTMZONE                     1125
#define IDC_SPIN1                       1126
#define IDC_SPIN_UTMZONE                1126
#define IDC_ST_MSG                      1127
#define IDC_ST_HELP                     1128
#define IDC_ST_COUNT                    1129
#define IDC_ST_MSGHDR                   1130
#define IDC_SKIPNEXT                    1131
#define IDC_ST_FILEMSG                  1132
#define IDC_ST_ADDING                   1133
#define IDC_ANTIALIAS                   1134
#define IDC_SPINSIZE_VEC                1135
#define IDC_EDIT_VEC_SZ                 1136
#define IDC_ST_FILLCLR                  1137
#define IDC_ST_INTOPACITY               1138
#define IDC_ST_POLYINT                  1139
#define IDC_ST_INTOPACITY2              1139
#define IDC_ST_POLYLINE                 1140
#define IDC_ST_RATIO                    1141
#define IDC_EDIT_IDXSEPTH               1141
#define IDC_EDIT_IDXDEPTH               1141
#define IDC_RATIO                       1142
#define IDC_SPIN_IDXDEPTH               1142
#define IDC_CHECK1                      1143
#define IDC_OPEN_IMAGE                  1143
#define IDC_KEEP_LAYOUT                 1143
#define IDC_CHK_TOOLBAR                 1143
#define IDC_MAKE_SIMILAR                1143
#define IDC_SUPPRESS_TS                 1143
#define IDC_MARK_PT                     1143
#define IDC_INCLUDE_SHP                 1143
#define IDC_ADDSHP                      1143
#define IDC_AUTOTRKSTART                1143
#define IDC_AUTORECORDSTART             1143
#define IDC_GET_SSIM                    1143
#define IDC_OPENFILE                    1143
#define IDC_OPEN_EXPORTED               1143
#define IDC_USE_INDEX                   1143
#define IDC_TEST_MEMOS                  1143
#define IDC_MATCH_CASE                  1143
#define IDC_ST_DENOM                    1144
#define IDC_TEST_MEMOS2                 1144
#define IDC_MATCH_WORD                  1144
#define IDC                             1145
#define IDC_ST_RATIO_BOX                1145
#define IDC_CHECK2                      1146
#define IDC_INC_SCALE                   1146
#define IDC_PREVIEW                     1146
#define IDC_INCLUDE_LINKED              1146
#define IDC_EXTENDED                    1146
#define IDC_BUTTON2                     1147
#define IDC_HELPCONTENTS                1147
#define IDC_REMOVE_REC                  1147
#define IDC_COPYLOC                     1147
#define IDC_UPDATE                      1147
#define IDC_ST_TITLE                    1148
#define IDC_PASTELOC                    1148
#define IDC_COPYLOC2                    1148
#define IDC_CLEARLOG                    1148
#define IDC_UNDELETED                   1149
#define IDC_PAUSELOG                    1149
#define IDC_DELETED                     1150
#define IDC_EXAMPLE                     1150
#define IDC_EXAMPLE0                    1150
#define IDC_CLEARLOG2                   1150
#define IDC_SAVELOG                     1150
#define IDC_DELETED2                    1151
#define IDC_ALLRECORDS                  1151
#define IDC_ST_INFO                     1151
#define IDC_BROKEN_LINK                 1152
#define IDC_EXAMPLE1                    1152
#define IDC_REPLACEMENT                 1153
#define IDC_ST_RECORD                   1153
#define IDC_OPACITY_IMG                 1153
#define IDC_USE_TRANSCLR                1154
#define IDC_TRANSCLR                    1155
#define IDC_ST_OPACITY_IMG              1156
#define IDC_TOLERANCE                   1158
#define IDC_TOLERANCE2                  1159
#define IDC_TOLERANCE3                  1160
#define IDC_TOLERANCE4                  1161
#define IDC_TOLERANCE5                  1162
#define IDC_TOLERANCE6                  1163
#define IDC_LAYERS_LIST                 1164
#define IDC_STRIP_RTF                   1164
#define IDC_ST_TOLERANCE                1165
#define IDC_ST_MSGFINISH                1166
#define IDC_URLCOMBO                    1167
#define IDC_SAVEASDFLT                  1169
#define IDC_ST_OUTOFZONE                1170
#define IDC_COLUMNTREE                  1171
#define IDC_ST_LOOKIN                   1172
#define IDC_KEY_FIELD                   1173
#define IDC_SHP_REF                     1174
#define IDC_SHP_CAND                    1175
#define IDC_SHP_COMP                    1176
#define IDC_ST_STATUS                   1179
#define IDC_ST_STATUS2                  1180
#define IDC_ST_SCANNING                 1180
#define IDC_ST_COMPLETE                 1181
#define IDC_ST_POSITION                 1182
#define IDC_ST_STATUS3                  1183
#define IDC_ST_SATSUSED                 1183
#define IDC_MINIMIZE                    1184
#define IDC_HDOP                        1186
#define IDC_ST_HDOP                     1186
#define IDC_ST_GROUP                    1187
#define IDC_ST_HDOP2                    1188
#define IDC_ST_ALT                      1188
#define IDC_COLORFRM_BKGND              1189
#define IDC_ST_ALLPOINTS_LBL            1190
#define IDC_ST_HIGHLIGHTED_LBL          1191
#define IDC_ST_BKGCOLOR_LBL             1192
#define IDC_ST_MSIZE_LBL                1193
#define IDC_ST_OUTLINE                  1194
#define IDC_ST_INTERIOR                 1195
#define IDC_ST_SHAPE                    1196
#define IDC_RADIO1                      1197
#define IDC_RADIO2                      1198
#define IDC_ST_TRACKLBL                 1198
#define IDC_RADIO3                      1199
#define IDC_ST_TRACKCNT                 1199
#define IDC_CONFIRMCNT                  1200
#define IDC_LOGOUTDATED                 1202
#define IDC_WEBP_CBQUALITY              1204
#define IDC_ST_IGNORED                  1205
#define IDC_JP2K_RATE                   1206
#define IDC_JP2K_CBRATE                 1206
#define IDC_FLDS_COMPARED               1206
#define IDC_FLDS_IGNORED                1207
#define IDC_INCLUDE_ALL                 1208
#define IDC_ST_DEPTH                    1209
#define IDC_BROWSE_SRC                  1213
#define IDC_ST_TXTCOMP                  1214
#define IDC_EDIT_PASTE                  1214
#define IDC_PROGRESS1                   1216
#define IDC_ST_FIELD                    1218
#define IDC_ST_CAUTION                  1222
#define IDC_YES                         1223
#define IDC_FALSE                       1224
#define IDC_ST_SETLOGICAL               1225
#define IDC_SCROLLBAR1                  1226
#define ID_Menu                         32771
#define ID_SORTASCENDING_SORTDESCENDING 32771
#define ID_VIEW_ZOOMIN                  32772
#define ID_SORTASCENDING_SORTASCENDING  32772
#define ID_VIEW_ZOOMOUT                 32773
#define ID_SORTDESCENDING               32773
#define ID_VIEW_PAN                     32774
#define ID_SORTASCENDING                32774
#define ID_FILE_PROPERTIES              32775
#define ID_VIEW_NOZOOM                  32776
#define ID_CHKCOLUMNS                   32776
#define ID_AVERAGE_COLORS               32777
#define IDR_VIEW_CONTEXT                32784
#define ID_CONTEXT_NOZOOM               32785
#define ID_VIEW_FULL                    32786
#define ID_CONTEXT_ZOOM25               32788
#define ID_CONTEXT_ZOOM50               32790
#define ID_CONTEXT_ZOOM12               32792
#define ID_CONTEXT_ZOOM6_25             32794
#define ID_CONTEXT_ZOOM3_125            32796
#define ID_CONTEXT_ZOOMOUT              32797
#define ID_CONTEXT_ZOOMIN               32798
#define ID__ZOOMTOLEVEL                 32801
#define ID_CTR_ONPOINT                  32802
#define ID_SYNC_ONPOINT                 32805
#define ID_FIT_IMAGE                    32808
#define ID_CONTEXT_ZOOM_SPECIFY         32813
#define ID_TOOLMEASURE                  32974
#define ID_OPTIONS_SHOWOUTLINES         32975
#define ID_FIT_EXTENT                   32976
#define ID__ZOOMTOLAYER                 32977
#define ID_MOVELAYERTOTOP               32983
#define ID_ZOOMTOLAYER                  32985
#define ID_OUTLINELAYER                 32986
#define ID_MOVELAYERTOBOTTOM            32987
#define ID_OPTIONS_SHOWSELECTED         32989
#define ID_HIDEMARKERS                  32993
#define ID_HIDELABELS                   32994
#define ID_SHOW_MARKERS                 32997
#define ID_SHOW_LABELS                  32998
#define ID_TRUNCATEOVERVIEWS            33001
#define ID_FILE_TRUNCATE                33002
#define ID_EDITTITLE                    33005
#define ID_ZOOM_BACK                    33006
#define ID_ZOOM_FORWARD                 33007
#define ID_MEA                          33009
#define ID_OPTIONS_BKCOLOR              33011
#define ID_FILE_CONVERT                 33012
#define ID_EDIT_SHAPE                   33013
#define ID_SHOW_CENTER                  33014
#define ID_SHOW_DELETE                  33015
#define ID_Menu33017                    33017
#define ID_TOOLSELECT                   33019
#define ID_VIEW_DEFAULT                 33021
#define ID_SHOW_COPYLOC                 33022
#define ID_SHOW_PASTELOC                33023
#define ID_Menu33024                    33024
#define ID_OPTIONS_MOUSESCROLLWHEELBEHAVIOR 33025
#define ID_ZOOMFROMCENTER               33026
#define ID_ZOOMFROMCURSOR               33028
#define ID_Menu33029                    33029
#define ID_ZOOMFORWARDIN                33031
#define ID_ZOOMFORWARDOUT               33032
#define ID_FINDLABEL                    33033
#define ID_WINDOW_CLOSEALL              33038
#define ID_FILE_CLOSEALL                33040
#define ID_ADDLAYER                     33041
#define ID_UNSELECT                     33042
#define ID_CLEAREDITED                  33043
#define ID_SHOW_CLEAREDITED             33044
#define ID_SHOW_UNSELECT                33045
#define ID_Menu33046                    33046
#define ID_Menu33047                    33047
#define ID_SELECT_NEW                   33048
#define ID_SELECT_ALLEDITED             33049
#define ID_SELECT_EDITED                33050
#define ID_CLEAR_EDITFLAGS              33051
#define ID_TOOL_SELECT                  33058
#define ID_Menu33059                    33059
#define ID_OPENEDITABLE                 33060
#define ID_SELECT_RELOCATED             33062
#define ID_PREF_OPENLAST                33063
#define ID_Menu33064                    33064
#define ID_PREF_OPENMAXIMIZED           33065
#define ID_SELECT_DELETED               33070
#define ID_SELECT_ADD                   33071
#define ID_EXPORT_PNG                   33073
#define ID_Menu33077                    33077
#define ID_SHOW_FILENAMES               33078
#define ID_SETSELECTEDMARKER            33079
#define ID_BRANCHSYMBOLS                33082
#define ID_Menu33083                    33083
#define ID_PREFERENCESFORTHISDOCUMENT_SCALEUNITS 33084
#define ID_SCALEUNITS_METERS            33085
#define ID_SCALEUNITS_FEET              33086
#define ID_FORMAT_PLAIN                 33090
#define ID_FORMAT_RTF                   33091
#define ID_MEMOTEXTEDITORDEFAULTS_DEFAULTFONT 33094
#define ID_MEMO_DEFAULTS                33095
#define ID_Menu33096                    33096
#define ID_Menu33099                    33099
#define ID_HIGHLIGHTEDMARKER            33101
#define ID__INSERT                      33106
#define ID_INSERT_LINKTOLOCALFILE       33107
#define ID_INS_LINKTOFILE               33108
#define ID_LAUNCH_GE                    33110
#define ID_OPTIONS_GE                   33111
#define ID_HELP_OPENINTROTEXT           33112
#define ID_HELP_OPENINTRO               33113
#define ID_HELP_OPENREADME              33114
#define ID__LOCATEPOINTINGOOGLEEARTH    33115
#define ID_PREFERENCES_GOOG             33116
#define ID_PREFERENCES_GE               33117
#define ID_MODIFIED                     33118
#define ID_SELECT_MODIFIED              33119
#define ID_SELECT_EDITEDONLY            33120
#define ID_SAVETOFILE                   33121
#define ID_PREFERENCES_EDITOR           33122
#define ID_PREF_EDITORNAME              33123
#define ID_OPEN_TABLE                   33125
#define ID__OPENATTRIBUTETABLE          33126
#define ID__OPEN_TABLE                  33127
#define ID_MOVETOTOP                    33128
#define ID_CENTER_VIEW                  33129
#define ID_ALLOW_EDITS                  33130
#define ID__EXPORT                      33131
#define ID_EXPORT_TABLEASTEXT           33132
#define ID_EXPORT_TEXT                  33133
#define ID__ADDTOSELECTEDPOINTSET       33134
#define ID__ADDTO_SELECTED              33135
#define ID_MOVETO_TOP                   33136
#define ID__ZOOMVIEWTOFEATURE           33137
#define ID_ZOOM_VIEW                    33138
#define ID_ZOOM_BRANCH                  33139
#define ID__OPENASSELECTEDPOINTS        33140
#define ID_OPENASSELECTED               33141
#define ID_SE                           33142
#define ID__REMOVEFROMTABLE             33143
#define ID_Menu33144                    33144
#define ID_SELECT_ALL                   33145
#define ID_REMOVEFROMTABLE              33146
#define ID_ADDTO_SELECTED               33147
#define ID__REPLACESELECTED             33148
#define ID__POINTS                      33149
#define ID__REPLACE_SELECTED            33150
#define ID_REPLACE_SELECTED             33151
#define ID__INVERTSELECTION             33152
#define ID_INVERTSELECTION              33153
#define ID_RESTOREVIEW                  33154
#define ID_IMG_PROPERTIRS               33155
#define ID_IMG_PROPERTIES               33156
#define ID_IMG_REMOVE                   33157
#define ID_Menu33158                    33158
#define ID_IMG_INSERT                   33159
#define ID_IMG                          33160
#define _REMOVE                         33161
#define ID_SETTITLE                     33162
#define ID_Menu33163                    33163
#define ID_IMG_COLLECTION               33164
#define ID__REMOVEALL                   33165
#define ID_REMOVEALL                    33166
#define ID__PASTE                       33167
#define ID__OPENCONTAININGFOLDER        33168
#define ID_OPENFOLDER                   33169
#define ID_PREFERENCESFORTHISDOCUMENT_COORDINATESDISPLAYEDONSTATUSBAR 33170
#define ID_DISPLAY_UTM                  33171
#define ID_DISPLAY_LATLONG              33172
#define ID_PREFERENCESFORTHISDOCUMENT_  33173
#define ID_ELEVUNITS_FEET               33174
#define ID_Menu33175                    33175
#define ID_ELEVUNITS_METERS             33176
#define ID_PREFERENCESFORTHISDOCUMENT_DATUMDISPLAYEDONSTATUSBAR 33177
#define ID_DATUMTOGGLED_1               33178
#define ID_DATUMDISPLAYEDONSTATUSBAR_NAD27 33179
#define ID_DATUMTOGGLED_2               33180
#define ID_DATUMTOGGLE_1                33181
#define ID_DATUMTOGGLE_2                33182
#define ID_LINKTEST                     33183
#define ID__PASTELAYER                  33184
#define ID_FILE_EXPORTPROJECTASZIP      33185
#define ID_FILE_EXPORTZIP               33186
#define ID_EXPORT_ZIP                   33187
#define ID_PREFERENCES_MARKERFORSELECTEDPOINTS 33188
#define ID_DELETE_RECORDS               33189
#define ID_UNDELETE_RECORDS             33190
#define ID__LOCATEINGOOGLEMAPS          33192
#define ID__LAUNCH_MAPS                 33193
#define ID__LAUNCH_GM                   33194
#define ID__LOCATEINGOOGLEMAPS33195     33195
#define ID_WEB_FORMAT                   33196
#define ID_WEBMAP_FORMAT                33197
#define ID__LOCATEAT                    33198
#define ID_HELP_OPENRELEASENOTES        33199
#define ID_CLOSE_LAYER                  33200
#define ID_CLOSE_AND_DELETE             33201
#define ID_Menu33202                    33202
#define ID__IMAGEOPACITY                33203
#define IDC_IMAGE_OPACITY               33204
#define ID_IMAGE_OPACITY                33205
#define ID_EXPORT_XLS                   33206
#define ID__LOCATEATMAPPIN              33208
#define ID_LAUNCH_URL                   33209
#define ID_OPTIONS_URL                  33210
#define ID_OPTIONS_WEBMAP               33211
#define ID__LOCATEATMAPPINGSITE         33212
#define ID_LOCATEATMAPPINGSITE_FLYDIRECT 33213
#define ID__VIEWPOINTATMAPPINGSITE      33214
#define ID_Menu33215                    33215
#define ID_CTR_ONPOSITION               33216
#define ID_SAVE_HISTORY                 33217
#define ID_Menu33219                    33219
#define ID__INSERTFOLDER                33220
#define ID_INSERTFOLDER_ABOVE           33221
#define ID_FOLDER_ABOVE                 33222
#define ID_INSERTFOLDER_BELOW           33223
#define ID_FOLDER_PARENT                33224
#define ID_FOLDER_BELOW                 33225
#define ID_LAYERS_ABOVE                 33226
#define ID_LAYERS_BELOW                 33227
#define ID_LAYERS_WITHIN                33228
#define ID_REMOVEFOLDER_KEEPCONTENTS    33229
#define ID_REMOVE_PARENT                33230
#define ID_FOLDER_CHILD                 33231
#define ID__REMOVEFOLDER                33232
#define ID_PREFERENCESFORTHISDOCUMENT_SAVEANDRESTORELAYERWINDOWSIZE 33233
#define ID_SAVE_LAYERWINDOW             33234
#define ID_MOVETOTOP_MOVETOBOTTOM       33235
#define ID_MOVETOBOTTOM_MOVETOTOP       33236
#define ID_MOVETOBOTTOM_MOVETOBOTTOM    33237
#define ID_MOVETOBOTTOM                 33238
#define IDR_COLTABLE_CONTEXT            33239
#define ID_COMPARE_SHP                  33241
#define ID__COMPAREWITHOTHERSHAPE       33242
#define ID_PREFERENCES_GPSTRACKINGOPTIONS 33243
#define ID_GPSTRACKINGOPTIONS_PORTSETUP 33244
#define ID_GPS_PORTSETUP                33245
#define ID_PREFERENCES_GPSTRACKINGOPTIONS33246 33246
#define ID_VIEW_STARTGPSTRACKING        33247
#define ID_GPS_TRACKING                 33248
#define ID_GPS_CENTER                   33250
#define ID_GPS_CONNECTION               33254
#define ID_GPS_GPSTRACKINGOPTIONS       33255
#define ID_GPS_OPTIONS                  33256
#define ID_GPS_CENTERVIEWONGPSPOSITION  33257
#define ID_GPS_ENABLETRACKING           33258
#define ID__ENA                         33259
#define ID_TRACKINGOPTIONS_GPSPLACEMARKSYMBOL 33260
#define ID_GPS_SYMBOL                   33261
#define ID_GPS_RECORDTRACKLINE          33262
#define ID_GPS_RECORDTRACK              33263
#define ID_GPS_DISPLAYTRAC              33264
#define ID_GPS_DISPLAYTRACK             33265
#define ID_GPS_ENABLEAUTOCENTERING      33266
#define ID_GPS_ENABLECENTERING          33267
#define ID_GPS_CLEARTRACK               33268
#define ID_VIEW_GPSTRACKINGOPTIONSFORVIEW 33269
#define ID__REPLACEWITHFILE             33275
#define ID__COMPAREWITHFILE             33276
#define ID_TABLE_FILL                   33279
#define ID__TESTMEMOFIELDINTEGRITY      33283
#define ID_TEST_MEMOS                   33284
#define ID__REPLACE                     33285
#define ID_REPL_TEXT                    33286
#define ID_TABLE_REPL                   33287
#define ID_SHOW_SETUNLOCATED            33288
#define ID_APPENDLAYER_0                34000
#define ID_APPENDLAYER_1                34001
#define ID_APPENDLAYER_2                34002
#define ID_APPENDLAYER_3                34003
#define ID_APPENDLAYER_4                34004
#define ID_APPENDLAYER_5                34005
#define ID_APPENDLAYER_6                34006
#define ID_APPENDLAYER_7                34007
#define ID_APPENDLAYER_8                34008
#define ID_APPENDLAYER_9                34009
#define ID_APPENDLAYER_N                34010
#define ID_SHOWRULER                    40005
#define ID_SHOWTOOLBAR                  40006
#define ID_EDIT_SELECTALL               40007
#define ID_EDIT_CLEAR2                  57638
#define ID_INDICATOR4                   59140
#define ID_INDICATOR_SCALE              59140
#define ID_INDICATOR2                   59143
#define ID_INDICATOR_SIZE               59143
#define ID_INDICATOR3                   59144
#define ID_INDICATOR_ZOOM               59144
#define ID_INDICATOR1                   59145
#define ID_INDICATOR_DEG                59145
#define ID_INDICATOR0                   59146
#define ID_INDICATOR_DATUM              59146
#define ID_INDICATOR_XY                 59147
#define IDS_ERR_BADFLT2                 61286
#define IDS_ERR_BADFLT3                 61286
#define IDS_ERR_NODIR1                  61287

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        275
#define _APS_NEXT_COMMAND_VALUE         33289
#define _APS_NEXT_CONTROL_VALUE         1227
#define _APS_NEXT_SYMED_VALUE           182
#endif
#endif
