//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by kdu_winshow.rc
//
#define IDC_META_REVERT                 3
#define IDC_META_APPLY                  4
#define IDD_ABOUTBOX                    100
#define IDR_HTML_KD_PLAYCONTROL         103
#define IDR_MAINFRAME                   128
#define IDR_KDU_SHTYPE                  129
#define IDD_PROPERTIESBOX               131
#define IDD_PROPERTYHELP                132
#define IDD_CORE_MESSAGES               133
#define IDD_JPIP_OPEN                   135
#define IDD_META_STRUCTURE              138
#define IDD_METAEDIT                    139
#define IDC_META_CURSOR                 142
#define IDD_PLAY_CONTROL                144
#define IDD_METADATA_CATALOG            151
#define IDC_PROPERTIES_LIST             1006
#define IDC_MESSAGE                     1007
#define IDC_JPIP_HOST                   1008
#define IDC_JPIP_SERVER                 1008
#define IDC_JPIP_PORT                   1010
#define IDC_JPIP_PROXY                  1010
#define IDC_JPIP_FILE                   1011
#define IDC_JPIP_REQUEST                1011
#define IDC_JPIP_PROTOCOL               1012
#define IDC_JPIP_SESSION_TYPE           1012
#define IDC_JPIP_CHANNEL_TYPE           1012
#define IDC_JPIP_CACHE_DIR              1013
#define IDC_META_TREE                   1013
#define IDC_META_TEXT                   1015
#define ID_META_DELETE                  1016
#define IDC_META_DELETE                 1016
#define IDC_META_LABEL                  1021
#define IDC_META_XPOS                   1023
#define IDC_META_YPOS                   1024
#define IDC_META_WIDTH                  1025
#define IDC_META_HEIGHT                 1026
#define IDC_META_ELLIPTICAL             1027
#define IDC_META_RECTANGULAR            1028
#define IDC_META_STREAMS                1029
#define IDC_META_ADD_STREAM             1030
#define IDC_META_WHOLE_IMAGE            1031
#define IDC_META_RENDERED               1033
#define IDC_META_SPIN_STREAM            1034
#define IDC_META_REMOVE_STREAM          1035
#define IDC_META_BOX_TYPE               1037
#define IDC_PLAY_TRACK                  1038
#define IDC_PLAY_NEXT_TRACK             1039
#define IDC_META_LAYERS                 1040
#define IDC_PLAY_BASE_NATIVE            1040
#define IDC_META_ADD_LAYER              1041
#define IDC_PLAY_BASE_CUSTOM            1041
#define IDC_META_SPIN_LAYER             1042
#define IDC_EDIT1                       1042
#define IDC_PLAY_BASE_FPS               1042
#define IDC_META_REMOVE_LAYER           1043
#define IDC_PLAY_X1                     1043
#define IDC_PLAY_X2                     1044
#define IDC_PLAY_D2                     1045
#define IDC_PLAY_D4                     1046
#define IDC_PLAY_FRAME_PERIOD           1047
#define IDC_PLAY_FWD1                   1048
#define IDC_PLAY_FRAME                  1049
#define IDC_PLAY_PLAY                   1050
#define IDC_PLAY_STOP                   1051
#define IDC_PLAY_FWD5                   1052
#define IDC_PLAY_BACK1                  1053
#define IDC_PLAY_BACK5                  1054
#define IDC_PLAY_RESET                  1055
#define IDC_PLAY_REPEAT                 1056
#define IDC_PLAY_ONTRACK_PERCENT        1057
#define IDC_META_MULTI_REGION           1057
#define IDC_META_ENCODED                1058
#define IDC_META_BOX_EDITOR             1061
#define IDC_META_EXTERNAL_FILE          1062
#define IDC_META_SAVE_TO_FILE           1063
#define IDC_META_CHOOSE_FILE            1064
#define IDC_META_EDIT_FILE              1065
#define IDC_META_TEMPORARY_FILE         1066
#define IDC_META_PARENT                 1067
#define IDC_META_PREV                   1068
#define IDC_META_NEXT                   1069
#define IDC_META_DESCENDANTS            1070
#define IDC_META_ADD_CHILD              1071
#define IDC_META_METASHOW               1072
#define IDC_META_ADD_PARENT             1073
#define IDC_META_APPLY_AND_EXIT         1074
#define IDC_META_CANCEL                 1075
#define IDC_META_IS_LINK                1076
#define IDC_COMBO2                      1077
#define IDC_META_INTERNALIZE_LABEL      1082
#define IDC_META_PASTE                  1083
#define IDC_META_COPY_LINK              1084
#define IDC_META_CATALOG                1086
#define IDC_META_COPY_DESCENDANTS       1087
#define IDC_JPIP_FORCE_INTERACTIVE      1088
#define ID_VIEW_HFLIP                   32771
#define ID_VIEW_VFLIP                   32772
#define ID_VIEW_ROTATE                  32773
#define ID_VIEW_COUNTER_ROTATE          32774
#define ID_VIEW_RESTORE                 32775
#define ID_VIEW_ZOOM_OUT                32776
#define ID_VIEW_ZOOM_IN                 32777
#define ID_MODE_FUSSY                   32778
#define ID_MODE_RESILIENT               32779
#define ID_MODE_FAST                    32780
#define ID_VIEW_WIDEN                   32781
#define ID_VIEW_SHRINK                  32782
#define ID_FILE_PROPERTIES              32783
#define ID_COMPONENT1                   32784
#define ID_COMPONENT2                   32785
#define ID_COMPONENT3                   32786
#define ID_COMPONENT4                   32787
#define ID_MULTI_COMPONENT              32788
#define ID_LAYERS_LESS                  32789
#define ID_LAYERS_MORE                  32790
#define ID_MODE_RESILIENT_SOP           32791
#define ID_MODE_SEEKABLE                32792
#define ID_STATUS_TOGGLE                32793
#define ID_VIEW_REFRESH                 32794
#define ID_FILE_DISCONNECT              32795
#define ID_JPIP_OPEN                    32796
#define ID_COMPONENT_PREV               32797
#define ID_COMPONENT_NEXT               32798
#define ID_FOCUS_OFF                    32800
#define ID_FOCUS_CENTRE                 32801
#define ID_FOCUS_HIGHLIGHTING           32802
#define ID_FOCUS_WIDEN                  32803
#define ID_FOCUS_SHRINK                 32804
#define ID_FOCUS_LEFT                   32805
#define ID_FOCUS_RIGHT                  32806
#define ID_FOCUS_UP                     32807
#define ID_FOCUS_DOWN                   32808
#define ID_FILE_COMMENTS                32809
#define ID_VIEW_METADATA                32810
#define ID_IMAGE_NEXT                   32811
#define ID_IMAGE_PREV                   32812
#define ID_COMPOSITING_LAYER            32813
#define ID_META_ADD                     32814
#define ID_OVERLAY_ENABLED              32815
#define ID_OVERLAY_FLASHING             32816
#define ID_OVERLAY_TOGGLE               32817
#define ID_OVERLAY_DOUBLESIZE           32821
#define ID_OVERLAY_HALVESIZE            32823
#define ID_VIEW_OPTIMIZESCALE           32824
#define ID_VIEW_SINGLETRACK             32825
#define ID_TRACK_NEXT                   32826
#define ID_VIEW_PLAYCONTROL             32831
#define ID_VIEW_SCALE_X2                32840
#define ID_VIEW_SCALE_X1                32846
#define ID_MODE_WANT_CODESTREAM_COMPONENTS 32850
#define ID_MODES_SINGLETHREADED         32855
#define ID_MODES_MULTITHREADED          32856
#define ID_MODES_MORETHREADS            32857
#define ID_MODES_LESSTHREADS            32858
#define ID_MODES_AUTO                   32859
#define ID_MODES_AUTOTHREADS            32860
#define ID_MODES_DEFAULTTHREADS         32861
#define ID_MODES_RECOMMENDED_THREADS    32862
#define ID_FILE_SAVEASLINKED            32863
#define ID_FILE_SAVEASEMBEDDED          32864
#define ID_FILE_SAVEANDRELOAD           32865
#define ID_METADATA_ACTIVATEMETASHOW    32866
#define ID_METADATA_ADDMETADATA         32867
#define ID_FILE_OP                      32869
#define ID_FILE_SAVE32870               32870
#define ID_Menu                         32872
#define ID_VIEW_QUALITYLAYERS           32873
#define ID_VIEW_TOGGLESTATUSDISPLAY     32874
#define ID_PLAY_PLAYFORWARDS            32875
#define ID_PLAY_PLAYBACKWARDS           32876
#define ID_PLAY_STOP                    32877
#define ID_PLAY_REPEAT                  32878
#define ID_PLAY_NATIVEPLAYRATE          32879
#define ID_PLAY_SCALENATIVEPLAYRATEUP   32880
#define ID_PLAY_SCALENATIVEPLAYRATEDOWN 32881
#define ID_PLAY_CUSTOMFRAMERA           32882
#define ID_METADATA_SHOW                32884
#define ID_METADATA_CATALOG             32899
#define ID_METADATA_ADD                 32900
#define ID_METADATA_EDIT                32901
#define ID_METADATA_DELETE              32902
#define ID_METADATA_COPYLABEL           32903
#define ID_METADATA_COPYLINK            32904
#define ID_METADATA_CUT                 32905
#define ID_METADATA_PASTENEW            32906
#define ID_OVERLAY_RESTRICT             32907
#define ID_MODE_RECOMMENDED_THREADS     32908
#define ID_MODE_SINGLETHREADED          32909
#define ID_MODE_MULTITHREADED           32910
#define ID_MODE_MORETHREADS             32911
#define ID_MODE_LESSTHREADS             32912
#define ID_PLAY_STARTFORWARD            32916
#define ID_PLAY_STARTBACKWARD           32917
#define ID_PLAY_NATIVE                  32918
#define ID_PLAY_CUSTOM                  32921
#define ID_WINDOW_DUPLICATE             32924
#define ID_WINDOW_BROADCASTONCE         32925
#define ID_WINDOW_BROADCASTINDEFINITELY 32927
#define ID_FILE_OPENURL                 32936
#define ID_PLAY_FRAMERATEUP             32997
#define ID_PLAY_FRAMERATEDOWN           32998
#define ID_WINDOWS_NEXTWINDOW           32999
#define ID_WINDOW_NEXT                  33001
#define ID_FILE_CLOSEWINDOW             33002
#define ID_WINDOW_CLOSE                 33003
#define ID_METADATA_SHOWIMAGERYFORCATALOGSELECTION 33005
#define ID_METADATA_SWAPFOCUS           33009
#define ID_WINDOW_BROADCAST             33010
#define ID_VIEW_ZOOMINSLIGHTLY          33011
#define ID_VIEW_ZOOMOUTSLIGHTLY         33012
#define ID_VIEW_ZOOM_IN_SLIGHTLY        33013
#define ID_VIEW_ZOOM_OUT_SLIGHTLY       33014
#define ID_OVERLAY_LIGHTER              33018
#define ID_OVERLAY_HEAVIER              33019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         33020
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
