//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Walls.rc
//
#define IDS_ERR_DELETEOPEN              1
#define IDR_MAINFRAME                   2
#define IDC_VECTORS                     2
#define IDR_PRJTYPE                     3
#define IDC_F_UVEV                      3
#define IDC_CLEARCHKS                   3
#define IDC_FRAMEFONT                   3
#define ID_DUPEDIT                      3
#define IDC_LINKTOFILES                 3
#define IDC_EMAILZIP                    3
#define ID_NOFILE                       3
#define IDC_APPLY                       3
#define ID_DELETE_FILES                 3
#define IDS_PRJ_FILES                   4
#define IDC_NOTEFONT                    4
#define IDC_SCALEFONT                   4
#define ID_ABORT                        4
#define IDR_SRVTYPE                     5
#define IDC_TITLEFONT                   5
#define IDC_SWAPSETS                    5
#define IDS_SRV_FILES                   6
#define IDS_WALLS_FILEFILTER            6
#define IDC_LABELFONT                   6
#define IDS_TXT_FILES                   7
#define IDS_PRJ_FILENEW                 7
#define IDS_PRJ_FILEOPEN                8
#define IDS_PRJ_FILESAVEAS              9
#define IDR_COMPTYPE                    10
#define IDR_REVTYPE                     10
#define IDS_SEF_FILES                   11
#define IDS_IMPBROWSE                   12
#define IDS_EXE_FILES                   13
#define IDS_3DBROWSE                    14
#define IDS_MAPFORMAT16                 15
#define IDS_PRJ_ERRDRAG1                16
#define IDS_FMT_LST7                    16
#define IDS_ERR_PRJCOPYFILE             17
#define IDS_ERR_PRJCOPYFILE1            17
#define IDS_WRL_FILES                   18
#define IDS_ERR_PRJCOPYITEM             19
#define IDS_ERR_PRJCOPYOVER1            20
#define IDS_SVG_FILES                   20
#define IDS_SHP_FILES                   21
#define IDS_FILE_OPENEXIST              22
#define IDS_PRJ_OPENCHMOD1              23
#define IDS_PRJ_OPENCHMODN1             24
#define IDS_PRJ_CHMODCOUNT2             25
#define IDS_PRJ_CHMODCOUNT1             26
#define IDS_ERR_READONLY                27
#define IDS_ERR_CHMODRW1                28
#define IDS_DELETE_LOCKED1              29
#define IDS_DELETE_COUNT1               30
#define IDS_ERR_GRIDRELATIVE            31
#define IDS_STRING32                    32
#define IDS_ERR_NONUTMSHP               32
#define IDS_ERR_DATEELEV                33
#define IDS_NAMLSTFMTH_LL               34
#define IDS_SVG_BROWSE2                 35
#define IDS_LST_FILES                   61
#define IDD_ABOUTBOX                    100
#define IDC_VECTORLIST                  100
#define ID_MODELDATA                    100
#define IDD_CLOSELEVEL                  101
#define ID_OPEN_SEL                     101
#define IDD_EDITOPTIONS                 101
#define IDC_AVAILMEM                    101
#define ID_INDICATOR_COL                102
#define ID_COMPLETED                    102
#define IDC_GRIDLINES                   103
#define IDD_LINENODLG                   103
#define ID_INDICATOR_LINE               103
#define IDC_TABLINES                    104
#define ID_TRAV_TOGGLE                  104
#define IDC_LEVEL                       105
#define ID_NEW_BOOK                     105
#define IDC_EDIT1                       105
#define IDD_PRJSELECT                   106
#define IDC_WORKSPACE                   106
#define IDC_3DPATH                      106
#define IDC_MONTH                       106
#define ID_INDICATOR_UTM                106
#define IDC_DISTANCE_EXP                106
#define IDC_TO_NOTE                     106
#define ID_PRJ_VIEW                     107
#define IDC_DISKSPACE                   107
#define IDC_LONDEG                      107
#define IDC_DISTANCE_OFF                107
#define IDD_PRJITEM                     108
#define IDC_LATDEG                      108
#define IDC_MAXCOORDCHG                 108
#define ID_INDICATOR_PFXNAM             108
#define IDB_BITMAP1                     109
#define IDC_LONMIN                      109
#define IDD_DUPDLG                      110
#define IDC_LATMIN                      110
#define IDD_COMPDLG                     111
#define IDD_DIALOG1                     111
#define IDC_LONSEC10                    111
#define IDD_COMPDLG1                    112
#define IDD_TRAVDLG                     112
#define IDC_LATSEC10                    112
#define IDB_LIGHTBULB                   113
#define IDC_ZONE                        113
#define IDD_TIP                         114
#define IDC_LATMIN10                    114
#define IDC_TITLE                       115
#define IDC_LONMIN10                    115
#define IDC_NAME                        116
#define IDC_LATDEG10                    116
#define IDC_SURVEY                      117
#define IDD_IMPORTDLG                   117
#define IDC_LONDEG10                    117
#define IDC_BOOK                        118
#define IDC_USEGRID                     118
#define IDC_GRID_TYPE                   118
#define IDC_PATH                        118
#define IDD_PLOTDLG                     119
#define IDC_SURVEYBOOK                  119
#define IDC_GRID_INHERIT                119
#define IDBROWSE                        120
#define IDR_MAPTYPE                     121
#define IDC_ATTR                        121
#define IDC_OPTIONS                     121
#define ID_FORMATOPT                    121
#define IDBROWSE2                       121
#define IDC_SURVEYNOT                   121
#define IDC_NAMETEXT                    122
#define IDD_VIEWDIALOG                  122
#define IDC_DUPEDIT2                    123
#define IDD_MAPFORMAT                   123
#define IDC_DEFINESEG                   123
#define IDC_DUPEDIT1                    124
#define IDC_METERUNITS                  124
#define IDC_VECLIST                     125
#define IDD_SEGDLG                      125
#define IDC_DUPNAME2                    126
#define IDD_APPLYTOALL                  126
#define IDC_DUPNAME1                    127
#define IDD_GRIDOPTIONS                 127
#define IDD_PRJFINDDLG                  128
#define IDC_SURVEYS                     128
#define IDC_EDITVEC                     129
#define IDD_GRADIENT                    129
#define IDC_EDITLEN                     130
#define IDB_ROTATE                      130
#define IDD_PLTFINDDLG                  131
#define IDC_TOTALS                      132
#define IDD_STATDLG                     132
#define IDC_COMPONENTS                  133
#define IDC_NETWORKS                    133
#define IDC_COMPONENT                   133
#define IDD_VECLIMITS                   133
#define IDC_SYSTEMS                     134
#define IDD_EXPDLG                      134
#define IDD_3DEXPDLG                    134
#define IDC_TRAVERSE                    135
#define IDC_SEGMENTS                    135
#define IDB_BITMAP2                     135
#define IDC_FINISHED                    136
#define IDD_3DCONFIG                    136
#define IDC_FLOAT                       137
#define IDC_FLOATV                      137
#define IDC_FLOATH                      138
#define IDD_NETFINDDLG                  138
#define CG_IDS_TIPOFTHEDAY              139
#define IDC_STATMSG                     140
#define IDD_COPYFILE                    140
#define IDC_GRIDOPTIONS                 140
#define CG_IDS_TIPOFTHEDAYMENU          141
#define IDC_ISOLATED                    142
#define IDC_CURSOR1                     142
#define CG_IDS_DIDYOUKNOW               143
#define CG_IDS_TIPOFTHEDAYHELP          146
#define ID_SURVEYDBLCLK                 147
#define IDC_F_UVEH                      148
#define ID_TRAVDBLCLK                   148
#define IDC_HZLENGTH                    149
#define IDC_VTLENGTH                    150
#define IDR_PRJ_CONTEXT                 151
#define IDS_PRJ_NAD83UTM                151
#define IDD_MAPEXPORT                   152
#define IDS_PRJ_NAD27UTM                152
#define IDD_MAGREF                      153
#define IDS_PRJ_WGS84UTM                153
#define IDS_PRJ_NAD83GEO                154
#define IDD_ERRORDLG                    155
#define IDS_PRJ_WGS84GEO                155
#define IDC_CORRECTION                  156
#define IDD_PRJOPTIONS                  156
#define IDS_PRJ_NAD27GEO                156
#define IDC_PREVTRAV                    157
#define IDS_PRJ_WGS84UPSN               157
#define IDC_SYSTTL                      158
#define IDD_ITEM_GENERAL                158
#define IDS_PRJ_WGS84UPSS               158
#define IDC_NEXTTRAV                    159
#define IDC_IMPBROWSE                   159
#define IDC_LOOPS                       159
#define IDC_IMPPRJPATH                  160
#define IDD_ITEM_REFERENCE              160
#define IDC_IMPSEFPATH                  161
#define IDD_ITEM_OPTIONS                161
#define IDC_IMPLINECOUNT                162
#define IDD_EXPORTSEF                   162
#define IDC_IMPORTING                   163
#define IDC_PLTFRM                      163
#define IDD_EXPAVDLG                    163
#define IDC_TRAVPREV                    164
#define IDC_TRAVNEXT                    165
#define IDD_MOVEBRANCH                  165
#define IDC_SYSPREV                     166
#define IDR_MOV_CONTEXT                 166
#define IDC_SYSNEXT                     167
#define IDD_PAGEGRID                    167
#define IDC_SYSSTATIC                   168
#define IDC_TRAVSTATIC                  169
#define IDD_PAGEOFFDLG                  169
#define IDC_ZOOMIN                      170
#define IDC_ZOOMOUT                     171
#define IDD_LISTDLG                     171
#define IDC_DEFAULT                     172
#define IDC_EXTERNGRID                  173
#define IDC_EXTERNLINES                 173
#define IDC_EXTERNGRIDLINES             173
#define IDD_UPDATELINK                  173
#define ID_OPEN                         173
#define IDC_EXTERNLABELS                174
#define IDD_MARKERDLG                   174
#define ID_SAVEAS                       174
#define IDC_EXTERNFRAME                 175
#define IDC_EXTERNOPTIONS               176
#define IDC_EXTERNFLAGS                 176
#define IDC_PRINTOPTIONS                177
#define IDC_TRAVSELECTED                177
#define IDD_LRUDSTYLE                   177
#define IDC_PLANPROFILE                 178
#define IDC_EXTERNMARKERS               179
#define IDD_EXPSVGDLG                   179
#define IDC_CHGVIEW                     180
#define IDC_TRAVFLOATED                 181
#define IDC_PAGEOFFSETS                 181
#define IDC_VIEW                        182
#define IDC_WIDTH                       183
#define IDC_EXTERNNOTES                 184
#define IDC_ZOOMWIDTH                   185
#define IDC_SAVE                        185
#define IDC_EDITVIEW                    186
#define IDC_PANELVIEW                   186
#define IDC_RECALL                      186
#define IDC_DISCARD                     186
#define IDC_PANELWIDTH                  187
#define IDC_WALLS                       187
#define IDC_VECTORTHICK                 188
#define IDC_FRAMETHICK                  189
#define IDC_FRAMEWIDTH                  190
#define IDC_MARKERTHICK                 191
#define IDD_SVGADVANCED                 191
#define IDC_MARKERXOFF                  192
#define IDC_MARKERYOFF                  193
#define IDD_ZIPDLG                      193
#define IDC_FRAMETHICKTEXT              194
#define IDC_ST_FRAMETHICK               194
#define IDD_ZIPCREATED                  194
#define IDC_NOTE1TEXT                   195
#define IDC_MARKERSIZE                  195
#define IDD_GPSINDLG                    195
#define IDC_NOTE2TEXT                   196
#define IDC_FRAMEHEIGHT                 196
#define IDC_NOTETEXT                    197
#define IDC_LABELSPACE                  197
#define IDC_TICKTHICK                   198
#define IDC_TOPOFFTEXT                  199
#define IDC_FLAGSIZE                    199
#define IDR_MAP_CONTEXT                 199
#define IDC_TICKLENGTH                  200
#define IDR_MAP_FRAMEINFO               200
#define IDC_TICKINTERVAL                201
#define IDC_FLAGTHICK                   201
#define IDD_MAPHELP                     201
#define IDC_NORTHEASTRATIO              202
#define IDC_VECTORTHIN                  202
#define IDR_PLT_CONTEXT                 202
#define IDC_GRIDINTERVAL                203
#define IDC_EASTINTERVAL                203
#define IDC_GRIDINT                     203
#define IDD_LAUNCHFIND                  203
#define IDC_TITLEXOFF                   204
#define IDC_GRIDTHICK                   204
#define IDC_EASTOFFSET                  204
#define IDC_MEASURE                     204
#define IDC_TITLEYOFF                   205
#define IDC_HORZVERTRATIO               205
#define IDR_EDIT_CONTEXT                205
#define IDC_LEFTOFFTEXT                 206
#define IDC_VERTINTERVAL                206
#define IDD_DIALOG2                     206
#define IDC_TITLEVISIBLE                207
#define IDC_NORTHOFFSET                 207
#define IDD_FILESTATDLG                 207
#define IDC_FEETSCALE                   208
#define IDC_FEETUNITS                   208
#define IDC_VERTOFFSET                  208
#define IDR_SEG_CONTEXT                 208
#define IDC_HORZOFFSET                  209
#define IDD_SVGPROCESS                  209
#define IDC_GRIDNORTH                   211
#define IDD_NOTINLOOP                   211
#define IDR_TRAV_CONTEXT                212
#define IDC_LBLNAMES                    213
#define IDR_GEOM_CONTEXT                213
#define IDC_LBLHEIGHTS                  214
#define IDC_BROUSE_ATTR                 214
#define IDR_BAR_CONTEXT                 214
#define IDC_SEGFRM                      215
#define IDC_LBLPREFIXES                 215
#define IDR_IMAGE_JPEG                  219
#define IDC_IDENTIFY                    220
#define IDR_MAP_IDENTIFY                221
#define IDC_SEGDETACH                   222
#define IDD_VECTORINFO                  222
#define IDC_SEGDISABLE                  223
#define IDC_BKGCOLOR                    224
#define IDC_APPLYTOALL                  225
#define IDC_LINECOLOR                   226
#define IDB_UTM_UPS                     227
#define IDC_LINESTYLE                   228
#define IDI_MAGDLG                      228
#define IDC_LABELCOLOR                  229
#define IDD_RESIZEFRAME                 229
#define IDC_SYMBOLS                     230
#define IDD_OPENEXISTING                230
#define IDC_MARKERS                     231
#define IDD_MOVE_CONFIRM                231
#define IDC_NAMES                       232
#define IDC_SEGVECTORS                  233
#define IDD_DELETEDLG                   233
#define IDC_SEGLENGTH                   234
#define IDC_FLAGS                       235
#define IDC_NOTES                       236
#define IDC_ST_FRAME                    237
#define IDC_NOTECOLOR                   237
#define IDC_FLOORCOLOR                  238
#define IDC_ST_BRANCH                   239
#define IDC_ST_COLORS                   240
#define IDC_MARKERCOLOR                 240
#define IDC_ST_SEGMENT                  241
#define IDC_USESTYLES                   245
#define IDC_USECOLORS                   246
#define IDC_MONOCHROME                  246
#define IDC_USELABELPOS                 246
#define IDC_USELINEWIDTHS               247
#define IDC_PORTRAIT                    250
#define IDC_SHOWTITLE                   251
#define IDC_EXTERNUPDATE                252
#define IDHELP_PROP                     253
#define IDC_DISPLAY                     253
#define ID_SRV_IMPORT                   253
#define IDC_ST_VECTORS                  254
#define IDC_ST_FONTS                    255
#define IDC_ST_MARKERS                  256
#define IDC_ST_GRIDLINES                257
#define IDC_ST_TICKMARKS                257
#define IDC_ST_LABELS                   258
#define IDC_ST_TICKMARKS2               259
#define IDC_ST_LINEWIDTHS               259
#define IDC_ST_FLAGS                    260
#define IDC_ST_ZOOMWIDTH                261
#define IDC_ST_LINEWIDTHS2              261
#define IDC_ST_PLANS                    263
#define IDC_ST_PROFILES                 264
#define IDC_USETICKMARKS                265
#define IDC_ST_GRIDORIGIN               266
#define IDC_ENTERTABS                   267
#define IDC_TABINTERVAL                 268
#define IDC_FINDSTRING                  277
#define IDC_MATCHWHOLEWORD              278
#define IDC_REPLSTRING                  278
#define IDC_MATCHCASE                   279
#define IDC_SEARCHDETACHED              280
#define IDC_NUMCHECKED                  281
#define IDC_HOMETRAV                    282
#define IDC_USEREGEX                    282
#define IDC_ROTATELEFT                  283
#define IDC_ROTATERIGHT                 284
#define IDC_CENTEREAST                  284
#define IDC_CENTERNORTH                 285
#define IDC_CENTERUP                    286
#define IDC_PRINTWIDTH                  288
#define IDC_ST_FRAMEHEIGHT              290
#define IDC_ST_CENTEREAST               291
#define IDC_ST_CENTERNORTH              292
#define IDC_CENTERREF                   293
#define IDC_FINDSTATION                 296
#define IDC_NOCASE                      297
#define IDC_SCALERATIO                  300
#define IDC_SCALEWIDTH                  301
#define IDC_ST_SCALETYPE                302
#define IDC_APPLY_PROMPT                303
#define IDC_DETAILS                     304
#define IDC_NOTELIST                    307
#define IDC_REFSTATION                  308
#define IDC_HIGHSTATION                 309
#define IDC_HIGHPOINT                   310
#define IDC_LOWPOINT                    311
#define IDC_LOWSTATION                  312
#define IDC_DEPTH                       313
#define IDC_NUMVECS                     314
#define IDC_TTLENGTH                    315
#define IDC_PERCENT                     316
#define IDC_EXPORT3D                    317
#define IDC_NUMNOTES                    318
#define IDC_USEFEET                     319
#define IDC_NUMFLAGS                    319
#define IDC_ST_EASTINTERVAL             320
#define IDC_ARCVIEW                     320
#define IDC_ST_EASTOFFSET               321
#define IDC_EXPORT2D                    321
#define IDC_ST_NORTHOFFSET              322
#define IDC_ST_VERTINTERVAL             323
#define IDC_ST_HORZVERTRATIO            324
#define IDC_ST_VERTOFFSET               325
#define IDC_ST_HORZOFFSET               326
#define IDC_ST_TICKINTERVAL             327
#define IDC_TYPEUNITS                   328
#define IDC_DISTANCE                    329
#define IDC_AZIMUTH                     330
#define IDC_VERTANGLE                   331
#define IDC_SAVENAMES                   331
#define IDC_AUTOSEQ                     332
#define IDC_LOADVIEWER                  332
#define IDC_ST_UVE                      334
#define IDC_ST_LOOPS                    335
#define IDC_LOOPSH                      336
#define IDC_LOOPSV                      337
#define IDC_IMPCOMBINE                  337
#define IDC_3DVIEWER                    339
#define IDC_3DSTATUS                    340
#define IDC_FLAGSOLID                   342
#define IDC_FLAGTRIANGLE                343
#define IDC_FLAGSTYLE                   345
#define IDC_DISPLAYOPTIONS              346
#define IDC_SAVECOLORS                  348
#define IDC_SCALEVERT                   349
#define IDC_YESTOALL                    350
#define IDC_ELEVGRID                    350
#define IDC_NOTOALL                     351
#define IDC_DIMGRID                     354
#define IDC_ST_COMPONENTS               356
#define IDC_ST_SYSTEMS                  357
#define IDC_ST_TRAVERSES                358
#define IDC_ST_SURVEYS                  359
#define IDC_ST_ISOLATED                 360
#define IDC_ST_TOTALS                   361
#define IDC_ST_UVEH                     362
#define IDC_ST_UVEV                     363
#define IDC_ST_ORIGINAL                 364
#define IDC_ST_BEST                     365
#define IDC_ST_HZLEN                    366
#define IDC_ST_VTLEN                    367
#define IDC_ST_ENU                      368
#define IDC_ST_PREVNEXT                 369
#define IDC_ST_DSTAZVT                  370
#define IDC_ST_SURVEY                   371
#define IDC_HDR_TRAVDLG                 371
#define IDC_INCDSTAZVT                  372
#define IDC_ST_SEGMENTS                 373
#define IDC_HDR_COMPONENTS              374
#define IDC_HDR_SYSTEMS                 375
#define IDC_HDR_TRAVERSES               376
#define IDC_PATHNAME                    377
#define IDC_LABELINC                    380
#define IDC_SAVEVIEW                    381
#define IDC_YEAR                        384
#define IDC_ELEVATION                   388
#define IDC_DECLINATION                 389
#define IDC_SPIN_YEAR                   392
#define IDC_SPIN_MONTH                  393
#define IDC_SPIN_LONDEG                 394
#define IDC_SPIN_LATDEG                 395
#define IDC_SPIN_LONMIN                 396
#define IDC_SPIN_LATMIN                 397
#define IDC_SPIN_ZONE                   398
#define IDC_CONVERGENCE                 399
#define IDC_LATDIR                      400
#define IDC_LONDIR                      401
#define IDC_UTMUPS                      402
#define IDC_FMT_DMS                     403
#define IDC_FMT_DM                      404
#define IDC_FMT_D                       405
#define IDC_UTMEAST                     406
#define IDC_UTMNORTH                    407
#define IDC_CONVERGENCE2                408
#define IDC_INTENSITY                   408
#define IDC_DATUM                       410
#define IDC_ST_MIN                      411
#define IDC_ST_SEC                      412
#define IDC_ST_ERRMSG                   413
#define IDC_BUTTONOK                    415
#define IDC_ST_INVALID                  418
#define IDC_ST_INVALID2                 419
#define IDC_ST_LATLONZONE               419
#define IDC_PRJSETTINGS                 420
#define IDC_USEDATES                    421
#define IDC_USEGRIDCONV                 422
#define IDC_DATE_INHERIT                422
#define IDC_ST_DATUM                    423
#define IDC_ST_LATLON                   424
#define IDC_MAGDLG                      425
#define IDC_TO_MAGDLG                   425
#define IDC_ST_CONV                     426
#define IDC_FR_MAGDLG                   426
#define IDC_USEGRIDNORTH                427
#define IDC_ENTERKEY                    427
#define IDC_ST_ELEV                     427
#define IDC_PRESERVE_VERTICAL           430
#define IDC_PRESERVE_LENGTH             431
#define IDC_ST_UTM                      431
#define IDC_INHERIT_VERTICAL            432
#define IDC_INHERIT_LENGTH              433
#define IDC_REF_INHERIT                 434
#define IDC_INHERIT_VIEW                434
#define IDC_REF_CLEAR                   435
#define IDC_REF_CHANGE                  436
#define IDC_DATE_METHOD                 437
#define IDC_ST_TITLE                    438
#define IDC_CONV                        439
#define IDC_ST_FILENAME                 439
#define IDC_CONVERTPFX                  440
#define IDC_ST_SURVEYDATE               440
#define IDC_INCLUDEDET                  441
#define IDC_ST_FILEDATE                 441
#define IDC_FORCEFEET                   442
#define IDC_ST_ATTR                     442
#define IDC_ST_STATUS                   443
#define IDC_FIXEDCOLS                   444
#define IDC_SHPPATH                     444
#define IDC_SHP_VECTORS                 445
#define IDC_SHP_STATIONS                446
#define IDC_SHP_NOTES                   447
#define IDC_SHP_FLAGS                   448
#define IDC_SHP_GRID                    449
#define IDC_SHP_WALLS                   449
#define IDC_SHPBASE                     450
#define IDC_ST_COUNTER                  451
#define IDC_SHP_MERGEDCONTENT           451
#define IDC_UNITS                       452
#define IDC_SHP_DETAIL                  452
#define IDC_SHP_LEGEND                  453
#define IDC_PATHPREFIX                  455
#define IDC_PATHTEXT                    456
#define ID_REPLACEALL                   457
#define ID_SKIP                         458
#define IDC_STATICBOX                   459
#define IDC_SIZEDATE                    461
#define IDC_DATETGT                     461
#define IDC_DATESRC                     462
#define IDC_ST_PANEL                    463
#define IDC_PAGFRM                      464
#define IDC_LANDSCAPE                   467
#define IDC_ST_PRINTER                  469
#define IDC_SELECTALL                   472
#define IDC_CLEARALL                    473
#define IDC_PAGES                       475
#define IDC_INCHES                      479
#define IDC_CENTIMETERS                 480
#define IDC_ST_ONECM                    482
#define IDC_METERSPERCM                 483
#define IDC_ST_FRAMESIZE                485
#define IDC_ST_MAPSCALE                 486
#define IDC_ST_METERS                   486
#define IDC_ST_PRINTAREA                487
#define IDC_ST_GRIDUNITS                487
#define IDC_ST_TRUEORGRID               488
#define IDC_ST_VIEW                     488
#define IDC_ST_FTORMETERS               489
#define IDC_CENTEROFPAGE                490
#define IDC_LEFTOFFSET                  491
#define IDC_TOPOFFSET                   492
#define IDC_OVERLAP                     493
#define IDC_ST_PAGEUNITS                495
#define IDC_ST_CM1                      496
#define IDC_ST_CM2                      497
#define IDC_ST_CM3                      498
#define IDC_TYPVECTOR                   499
#define IDC_TYPNAME                     500
#define IDC_NOTEDONLY                   501
#define IDC_USEPAGESIZE                 502
#define IDC_GROUPBYFLAG                 502
#define IDC_ST_FRAMEWIDTH               503
#define IDC_GROUPBYLOC                  503
#define IDC_DECIMALS                    504
#define IDC_INSIDEFRAME                 505
#define IDC_LEGENDPOS                   506
#define IDC_WALLSURL                    509
#define IDC_UPDATELINK                  510
#define IDC_NEWURL                      511
#define IDC_LISTFLAGS                   513
#define IDC_MSOLID                      514
#define IDC_MOPAQUE                     515
#define IDC_MCLEAR                      516
#define IDC_MSIZE                       517
#define IDC_MTRANSPARENT                518
#define IDC_GETCOLOR                    521
#define IDC_FGCOLOR                     521
#define IDC_COLORFRM                    522
#define IDC_LINEWIDTH                   524
#define IDC_PRIORUP                     526
#define IDC_PRIORDOWN                   527
#define IDC_MSHAPE                      528
#define IDC_GETTT                       529
#define IDC_DISABLE                     530
#define IDC_ENABLE                      531
#define IDC_SPIN_MSIZE                  533
#define IDC_ST_FLAGLIST                 535
#define IDC_ST_MARKERSTYLE              537
#define IDC_LRUDSTYLE                   543
#define IDC_LRUDSOLID                   544
#define IDC_LRUDTICKS                   546
#define IDC_LRUDBOTH                    547
#define IDC_LRUDMARKERCLR               548
#define IDC_SPIN_ENLARGE                551
#define IDC_EDIT_ENLARGE                552
#define IDC_WALLSHPX                    553
#define IDC_2DPATH                      555
#define IDC_GRIDSUB                     556
#define IDC_EXECUTEW2D                  557
#define IDC_ST_3DCONFIG                 558
#define IDC_2DTITLE                     558
#define IDC_INDEXVECTORS                559
#define IDC_LENGTH_EXP                  559
#define IDC_ADJUSTABLE                  560
#define IDC_VECTOR_CNT                  560
#define IDC_DEFAULTS                    561
#define IDC_MERGEPATH                   561
#define IDC_ADVANCED                    562
#define IDC_MINVECLEN                   564
#define IDC_ST_PROGRESS                 565
#define IDC_INCLUDENTA                  566
#define IDC_OPENZIP                     567
#define IDC_ST_MESSAGE                  568
#define IDC_LAUNCHPROMPT                570
#define IDC_LAUNCHOPEN                  571
#define IDC_LAUNCHEDIT                  572
#define IDC_ST_LAUNCH                   573
#define IDC_ST_REVIEW                   574
#define IDC_HIDENOTES                   575
#define IDC_COMPORT                     576
#define IDC_TESTCOM                     577
#define IDC_WAYPOINTS                   580
#define IDC_TRACKS                      581
#define IDC_BOTHTYPES                   582
#define IDC_ST_TESTCOM                  583
#define ID_STARTDL                      585
#define IDC_LOCALTIME                   586
#define IDC_WRITECSV                    587
#define IDC_LAUNCHLB                    589
#define IDC_RESTRICT                    590
#define IDC_WPTDIST                     591
#define IDC_WAYPOINT                    592
#define IDC_TRKBREAK                    594
#define IDC_NORTHEAST                   596
#define IDC_NORTHWEST                   597
#define IDC_ST_LOCATION                 597
#define IDC_NORTH                       598
#define IDC_EAST                        599
#define IDC_ST_UPDATED                  599
#define IDC_SETSELECTED                 599
#define IDC_WEST                        600
#define IDC_SVG_USE                     600
#define IDC_SVG_PROCESS                 601
#define IDC_ST_SVG_STATUS               601
#define IDC_MINSEPARATION               602
#define IDC_THICKPENPTS                 603
#define IDC_3DTYPE                      604
#define IDC_ST_MINVALUE                 613
#define IDC_ST_MAXVALUE                 614
#define IDC_ST_STARTVALUE               615
#define IDC_ST_ENDVALUE                 616
#define IDC_RESET_PEGS                  617
#define IDC_LRUDBARS                    618
#define IDC_LRUDBOXES                   619
#define IDC_PROPERTIES                  620
#define IDC_FILE_EDIT                   621
#define IDC_VIEWSTATS                   622
#define IDC_FR_FLAGS                    623
#define IDC_TO_FLAGS                    624
#define IDC_FR_EAST                     625
#define IDC_TO_EAST                     626
#define IDC_FR_NORTH                    627
#define IDC_TO_NORTH                    628
#define IDC_FR_UP                       629
#define IDC_TO_UP                       630
#define IDC_FR_NOTE                     631
#define IDC_ST_FR_NAME                  632
#define IDC_ST_TO_NAME                  633
#define IDC_ST_EAST                     636
#define IDC_ST_NORTH                    637
#define IDC_ST_UP                       638
#define IDC_ST_NOTE                     640
#define IDC_SPIN_INCHES                 648
#define IDC_SAVEASDEFAULT               649
#define IDC_ST_PIXELWIDTH               650
#define IDC_INCHWIDTH                   651
#define IDC_ST_NUMVECS                  652
#define IDC_OPENEXISTING                653
#define IDC_ST_PATHNAME                 654
#define IDC_READONLY                    655
#define IDC_LRUDEXAG                    656
#define IDC_COMBO1                      657
#define IDC_EDIT_WIDTH                  658
#define IDC_UTM                         659
#define IDC_LATLONG                     660
#define IDC_EDIT_WIDTH2                 662
#define IDC_EDIT_HEIGHT                 662
#define IDC_ST_ZONE                     662
#define IDC_ST_NORTHING                 663
#define IDC_ST_UTMUPS                   664
#define IDC_ST_EASTING                  665
#define IDC_ZONE_DEC                    666
#define IDC_ZONE_INC                    667
#define IDC_ST_ZONECHAR                 670
#define IDC_CHECK1                      671
#define IDC_COPYSINGLE                  914
#define IDC_COPYMULTIPLE                915
#define ID_CHANGEFONT                   987
#define IDR_LISTICONS                   999
#define IDC_BULB                        1000
#define IDC_GRADIENT                    1000
#define IDC_STARTUP                     1001
#define IDC_SELPEG_POSITION             1001
#define IDC_NEXTTIP                     1002
#define IDC_NEWPEG_VALUE                1002
#define IDC_TELLMEMORE                  1003
#define IDC_SELPEG_COLOR                1003
#define IDC_TIPSTRING                   1004
#define IDC_PREVTIP                     1005
#define IDC_DEL_PEG                     1005
#define IDC_ADD_PEG                     1007
#define IDC_ST_NEWPOS                   1008
#define IDS_MEMTOTAL                    1009
#define IDC_NEWPEG_POSITION             1009
#define IDS_WORKSPACE                   1010
#define IDC_SELPEG_VALUE                1010
#define IDS_UNAVAILABLE                 1011
#define IDC_ST_SELPOS                   1011
#define IDC_ST_RANGETYPE                1014
#define IDC_ST_SELPEG                   1017
#define IDC_METHOD_COMBO                1023
#define IDC_NODROP                      1025
#define IDC_MOVESINGLE                  1026
#define IDC_MOVEMULTIPLE                1027
#define IDC_COPY                        1028
#define IDC_MOVE                        1029
#define IDS_STRING21039                 21039
#define ID_PRJ_EDITITEM                 32601
#define ID_PRJ_NEWITEM                  32602
#define ID_PRJ_DETACH                   32603
#define ID_CLOSEALL                     32768
#define ID_ENABLELINES                  32769
#define ID_GRIDSETTINGS                 32769
#define ID_CLOSESEL                     32770
#define ID_GOTOLINE                     32771
#define ID_DELITEMS                     32772
#define ID_OPENALL                      32773
#define ID_OPENSEL                      32774
#define ID_ENABLENAMES                  32775
#define ID_ENABELTITLES                 32776
#define IDS_PRJ_ERR_BADNAME1            32777
#define ID_BOOKFONT                     32778
#define ID_SURVEYFONT                   32779
#define ID_PRJ_NEW                      32780
#define PRJ_ERR_COMPARE                 32781
#define ID_PRJ_OPEN                     32782
#define IDS_VIEWDLGTITLE                32783
#define ID_DETACH_BRANCH                32784
#define IDS_ERR_NOT2NAMES               32785
#define IDS_ERR_VECNOFIND               32786
#define ID_PRJ_MRU_FILE1                32787
#define IDS_VRML_NOTIFY1                32787
#define ID_PRJ_MRU_FILE2                32788
#define IDS_ERR_NAMETOOLONG             32788
#define ID_PRJ_MRU_FILE3                32789
#define ID_EDITORFONT                   32789
#define ID_PRJ_MRU_FILE4                32790
#define ID_FIND_NEXT                    32790
#define ID_FIND_PREV                    32791
#define ID_PROJECT_NEW                  32792
#define ID_PROJECT_OPEN                 32793
#define ID_PROJECT_CLOSE                32794
#define ID_PROJECT_SAVE_AS              32795
#define ID_PROJECT_SAVE                 32796
#define ID_PROJECT_SEARCH               32797
#define ID_SURVEY_NEW                   32798
#define ID_SURVEY_OPEN                  32799
#define ID_SURVEY_CLOSE                 32800
#define ID_SURVEY_SAVE                  32801
#define ID_SURVEY_SAVE_AS               32802
#define ID_FILE_MRU_TEXT1               32803
#define ID_FILE_MRU_SRV1                32804
#define IDS_ERR_NOTLOOPVECTOR           32805
#define ID_PURGEITEM                    32806
#define IDS_ERR_PFXNONAME               32807
#define ID_PRJ_COMPILE                  32808
#define IDS_ERR_PFXNOFIND               32809
#define ID_PRJ_COMPILEITEM              32810
#define ID_FLAGITEM                     32811
#define ID_REVIEWITEM                   32812
#define ID_REVIEWLASTCOMPITEM           32813
#define ID_ENABLETITLES                 32814
#define ID_ENABLEBOTH                   32815
#define ID_OPTIONS_COMPILE              32816
#define ID_CHECKNAMES                   32817
#define IDS_SHP_NOTIFY3                 32818
#define ID_PURGEBRANCH                  32819
#define ID_REVIEWFONT                   32820
#define ID_IMPORT                       32821
#define ID_NULLIMPORT                   32822
#define ID_MAKENTC                      32823
#define ID_MAPFONT                      32824
#define ID_RECOMPILE                    32825
#define ID_EXTERNOPTIONS                32826
#define ID_PRINTOPTIONS                 32827
#define ID_DISPLAYOPTIONS               32828
#define ID_MAKETXT                      32829
#define IDS_SHPX_NOTIFY3                32829
#define ID_OPT_EDITSRV                  32830
#define ID_OPT_EDITOTHER                32831
#define ID_OPT_EDITCURRENT              32832
#define ID_PRINTLABELS                  32833
#define ID_SCREENLABELS                 32834
#define ID_ESCAPEKEY                    32835
#define IDS_SVG_NOTIFY1                 32835
#define ID_EDIT_AUTOPFX                 32836
#define ID_EDIT_AUTOSEQ                 32837
#define ID_EDIT_REVERSE                 32838
#define IDS_SVG_NOTIFY6                 32839
#define ID_WINDOW_CLOSEALL              32840
#define IDS_ERR_NOTLOOPVECTOR1          32841
#define ID_VECLIMITS                    32842
#define ID_SEGMENTSET                   32844
#define ID_SEGMENTCLR                   32845
#define ID_EDIT_DELETE                  32846
#define ID_FEETSET                      32847
#define ID_FEETCLR                      32848
#define ID_FILEEXPORT                   32849
#define ID_FILE_EXPORT                  32850
#define ID_VRML_CONFIG                  32851
#define ID_3D_CONFIG                    32852
#define ID_LAUNCH3D                     32853
#define ID_PRINTNOTES                   32854
#define ID_SCREENNOTES                  32855
#define ID_FRAMEFONT                    32856
#define ID_LAUNCHLST                    32857
#define ID_EDIT_LEAF                    32879
#define ID_MAP_EXPORT                   32881
#define ID_MAPEXPOPTIONS                32882
#define ID_EXPORTOPTIONS                32883
#define ID_EXPORTLABELS                 32884
#define ID_EXPORTNOTES                  32885
#define ID_SWITCHTOMAP                  32886
#define ID_MAGREF                       32888
#define ID_PRJSETTINGS                  32892
#define ID_EXPORTSEF                    32893
#define ID_PRJ_EXPORTITEM               32894
#define ID_DETAILS                      32895
#define ID_REFRESHBRANCH                32896
#define ID_COPYBRANCHFILES              32897
#define ID_MOVEBRANCHFILES              32898
#define ID_MOVEBRANCHLINKS              32899
#define ID_COPYBRANCHLINKS              32900
#define ID_MOVECOPYCANCEL               32901
#define ID_LAUNCHLOG                    32902
#define ID_MARKERSTYLE                  32905
#define ID_REVIEWLAST                   32906
#define ID_SVG_EXPORT                   32907
#define ID_2D_CONFIG                    32908
#define ID_BUTTON32918                  32918
#define ID_BUTTON32919                  32919
#define ID_BUTTON32920                  32920
#define ID_BUTTON32921                  32921
#define ID_BUTTON32924                  32924
#define ID_BUTTON32925                  32925
#define ID_BUTTON32926                  32926
#define ID_BUTTON32927                  32927
#define ID_BUTTON32928                  32928
#define ID_BUTTON32929                  32929
#define ID_BUTTON32930                  32930
#define ID_BUTTON32931                  32931
#define ID_BUTTON32932                  32932
#define ID_BUTTON32933                  32933
#define ID_BUTTON32934                  32934
#define ID_BUTTON32935                  32935
#define ID_BUTTON32936                  32936
#define ID_BUTTON32937                  32937
#define ID_BUTTON32938                  32938
#define ID_BUTTON32939                  32939
#define ID_BUTTON32940                  32940
#define ID_BUTTON32941                  32941
#define ID_LAUNCH2D                     32942
#define ID_BUTTON32943                  32943
#define ID_BUTTON32951                  32951
#define ID_BUTTON32953                  32953
#define ID_ZIPBACKUP                    32954
#define ID_GPS_DOWNLOAD                 32955
#define ID_MAP_ORIGINAL                 32956
#define ID_MAP_PREVIOUS                 32957
#define ID_MAP_ZOOMOUT                  32958
#define ID_MAP_ZOOMIN                   32959
#define ID_MAP_CENTER                   32960
#define ID_MAP_LABELS                   32961
#define ID_MAP_MARKERS                  32962
#define ID_MAP_FLAGS                    32963
#define ID_MAP_NOTES                    32964
#define ID_MAP_PASSAGE                  32965
#define ID_MAP_HELP                     32966
#define ID_MAP_VIEWHELP                 32967
#define ID_PLT_ZOOMIN                   32968
#define ID_PLT_ZOOMOUT                  32969
#define ID_PLT_PANTOHERE                32970
#define ID_PLT_DEFAULT                  32972
#define ID_PLT_RECALL                   32973
#define ID_BUTTON32974                  32974
#define ID_MEASUREDIST                  32975
#define ID_POPUP_MAP_PREFIXES           32977
#define ID_MAP_PREFIXES                 32978
#define ID_EDIT_PROPERTIES              32979
#define ID_MAP_VECTORS                  32980
#define ID_SORTBRANCH                   32981
#define ID_MAP_ELEVATIONS               32982
#define ID_LOCATEONMAP                  32983
#define ID_LOCATEINGEOM                 32984
#define ID_GO_EDIT                      32985
#define ID_FINDSTATION                  32986
#define ID_CLEARCHECKS                  32988
#define ID_EDIT_VECTOR                  32990
#define ID_LOCATEVECTOR                 32991
#define IDS_LST_BROWSE                  32992
#define ID_EDITVECTOR                   32993
#define ID_SORTBRANCHREV                32994
#define ID_BUTTON32995                  32995
#define ID_VECTORINFO                   32997
#define ID_RESIZEMAPFRAME               32999
#define ID_BUTTON33004                  33004
#define ID_EXPORT3D                     33005
#define ID_POPUP_WRITE                  33007
#define ID_WRITEPROTECT                 33010
#define ID_REMOVEPROTECTION             33011
#define ID_Menu                         33014
#define ID_EDIT_SELECTALL               33017
#define ID_POPUP_WRITEPROTECT           33019
#define ID_PRJ_SAVE                     57603
#define ID_PRJ_SAVE_AS                  57604
#define IDC_UPDATEFRAME                 57610
#define ID_INDICATOR_SEL                59141
#define IDS_ERR_TRUNCFILE               61216
#define IDS_ERR_TRUNCLINE1              61217
#define IDS_ERR_TRUNCTABS1              61218
#define IDS_ERR_FILESAVEOPEN            61219
#define IDS_ERR_FILEOPEN1               61220
#define IDS_ERR_LINESAVE1               61221
#define IDS_ERR_FILESAVEWRITE           61222
#define IDS_ERR_FILESAVEALLOC           61223
#define IDS_ERR_MAXLINLEN               61224
#define IDS_ERR_FILERES                 61225
#define IDS_ERR_MEMORY                  61226
#define IDS_ERR_CLIPCOPY                61227
#define IDS_ERR_MAXCLIPLINES            61228
#define IDS_ERR_LINESCLIPPED            61229
#define IDS_ERR_CLIPPASTE2              61230
#define IDS_ERR_MAXCLIPLINES1           61231
#define IDS_ERR_MAXLINES                61232
#define IDS_ERR_MAXLINTABS              61233
#define IDS_ERR_FILEOPENMEM             61234
#define IDS_ERR_SEARCH1                 61235
#define IDS_ERR_REPLACE1                61236
#define IDS_ERR_INCSEARCH1              61237
#define IDS_ERR_REPABORT1               61238
#define IDS_ERR_REPLINE1                61239
#define IDS_ERR_PROJECT2                61240
#define IDS_ERR_PROJECT4                61240
#define PRJ_ERR_MAXLEVELS               61241
#define PRJ_ERR_TRUNCATE                61242
#define PRJ_ERR_NOSRV1                  61243
#define PRJ_ERR_BADARG                  61244
#define PRJ_ERR_BADSEQ                  61245
#define PRJ_ERR_KEYWORD                 61246
#define PRJ_ERR_NOTAPRJ                 61247
#define IDS_PRJ_ERR_DROPTOSELF          61248
#define IDS_PRJ_ERR_LBSPACE             61249
#define IDS_PRJ_ERR_COMPARE             61250
#define IDS_PRJ_ERR_MAXLEVELS           61251
#define IDS_PRJ_ERR_COPYMEM             61252
#define IDS_PRJ_ERR_NOTITLE             61253
#define PRJ_ERR_NODIR                   61254
#define PRJ_ERR_NODIR1                  61254
#define PRJ_ERR_BADDIR                  61255
#define PRJ_ERR_DIRWORK                 61255
#define IDS_PRJ_ERR_COPYTOSELF          61256
#define IDS_ERR_NTVBUILD                61257
#define IDS_ERR_SRVOPEN                 61258
#define IDS_ERR_SRVTEXT                 61259
#define PRJ_ERR_ZEROCHK                 61260
#define IDS_PRJ_NTVPURGE                61261
#define IDS_PRJ_ERR_BADNAME             61261
#define IDS_ERR_NTVPURGE                61262
#define IDS_ERR_NTVPURGE1               61262
#define IDS_SRVOK3                      61263
#define PRJ_ERR_NOWRK1                  61264
#define PRJ_ERR_EOF                     61265
#define IDS_PRJ_ERR_BADPATH             61267
#define IDS_ERR_CONVRANGE               61267
#define IDS_ERR_TRXBUILD                61268
#define IDS_ERR_SRVDUP                  61269
#define IDS_ERR_NTVADJUST               61270
#define IDS_ERR_NTVEMPTY                61271
#define IDS_ERR_WORKFILE                61272
#define IDS_ERR_IMPNAME1                61273
#define IDS_ERR_PRJMEM                  61274
#define IDS_PRJ_FINDCOUNT2              61275
#define IDS_ERR_IMPPRJPATH1             61276
#define IDS_ERR_IMPSEFPATH1             61277
#define IDS_ITMBROWSE                   61278
#define IDS_ERR_IMPERRMSG1              61279
#define IDS_ERR_IMPLOADDLL1             61280
#define IDS_ERR_ZOOMLIMIT               61281
#define IDS_ERR_ZOOMRANGE               61282
#define IDS_ERR_MAKEFRAME               61283
#define IDS_ERR_MAKEFRAME1              61283
#define IDS_ERR_BADVIEW                 61284
#define IDS_ERR_BADINT2                 61285
#define IDS_ERR_BADFLT2                 61286
#define IDS_ERR_SEGSIZE                 61287
#define IDS_ERR_TRXSAVE1                61288
#define IDS_ERR_BADWORK                 61289
#define IDS_ERR_WORKSPACE               61290
#define IDS_PRJ_FINDCOUNT1              61291
#define IDS_PRJ_FINDONE1                61292
#define IDS_ERR_REOPENWORK2             61293
#define IDS_COMP_GEOMETRY               61294
#define IDS_COMP_STATISTICS             61295
#define IDS_COMP_SYSTEM                 61296
#define IDS_ERR_BADFLOAT                61297
#define IDS_ERR_MAPLOCATE1              61298
#define IDS_ERR_EMPTYNAME               61299
#define IDS_PRJ_ERR_PATH                61300
#define IDS_PRJ_COPYITEM1               61300
#define IDS_PRJ_COPYITEM                61300
#define IDS_STAT_TITLE                  61301
#define IDS_ERR_SRVOPTION               61302
#define IDS_STAT_UNITS                  61303
#define IDS_VECLSTFMT                   61304
#define IDS_EXPORT3DMSG                 61305
#define IDS_EXP3DHDR                    61306
#define IDS_ERR_EXECUTE1                61306
#define IDS_TITLE_EDITOPT               61307
#define PRJ_ERR_DIRPROJECT              61308
#define IDS_ERR_NOVECTORS               61309
#define IDS_ERR_EXECUTE                 61310
#define IDS_PRJ_NO3DFILE                61311
#define IDS_PRJ_ITEMPATH1               61312
#define IDS_PRJ_MOVEBRANCH              61312
#define IDS_PRJ_SELDIR                  61312
#define IDS_PRJ_LSTNONE1                61313
#define IDS_PRJ_LSTDATE1                61314
#define IDS_PRJ_3DDATE1                 61315
#define IDS_OTHERBROWSE                 61315
#define IDS_PRJ_UNAVAILABLE             61316
#define IDS_ERR_PRINTSCALE2             61317
#define IDS_EMF_FILES                   61318
#define IDS_WMF_FILES                   61319
#define IDS_MAPEXP_BROWSE               61320
#define IDS_MAPEXP_OK                   61321
#define IDS_MAPEXP_BAD                  61322
#define IDS_ERR_METARES                 61323
#define IDS_ERR_MAG_LOAD                61324
#define IDS_ERR_MAG_INIT                61325
#define IDS_ERR_MAGRANGE2               61326
#define IDS_ERR_DATEDECL3               61327
#define IDS_VECLSTFMTG                  61328
#define IDS_VECLSTFMTH                  61329
#define IDS_SEF_BROWSE                  61330
#define IDS_WRL_BROWSE                  61331
#define IDS_OK_EXPSEF5                  61332
#define IDS_ERR_EXPCLOSE1               61333
#define IDS_ERR_EXPTEXT3                61334
#define IDS_ERR_EXPTEXT1                61335
#define IDS_SHP_BROWSE                  61336
#define IDS_SHP_NOTYPES                 61337
#define IDS_PRJ_ERR_NAMEPFX             61338
#define IDS_ERR_MAXPAGES                61339
#define IDS_ERR_PAGEZOOM                61340
#define IDS_ERR_MAGRANGEF2              61341
#define IDS_ERR_NOPAGES                 61342
#define IDS_PRJ_LOGNONE1                61343
#define IDS_PRJ_ERRORLOG                61344
#define IDS_NAMLSTFMTH                  61345
#define IDS_PRJ_FRAMECHG                61346
#define IDS_ERR_NOPRINTER1              61347
#define IDS_ERR_NOPRINTER               61348
#define IDS_SVG_BROWSE                  61349
#define IDS_ERR_BADPRINTER1             61350
#define IDS_ERR_SRVNODATUM2             61351
#define IDS_ERR_BADZONE2                61353
#define IDS_ERR_IMPVERSION1             61355
#define IDS_ERR_WRTNTW1                 61356
#define IDS_PRJ_2DDATE1                 61357
#define IDS_3DCONFIG3                   61358
#define IDS_ERR_SVGPROFILE              61359
#define IDS_ERR_SVGCARDINAL             61360
#define IDS_ERR_NOTENTW1                61360
#define IDS_ERR_SVGEXTENSION            61361
#define IDS_ERR_FILE_RW                 61362
#define IDS_SVG_EXISTDLG                61364
#define IDS_ERR_MERGEFILE1              61365
#define IDS_ERR_MERGEFILE               61366
#define IDS_ERR_NOGEOREF                61367
#define IDS_PRJ_NO2DFILE                61368
#define IDS_ERR_GRIDFEET                61369
#define IDS_ZIPDLGFMT                   61370
#define IDS_ZIP_FILES                   61371
#define IDS_ZIP_BROWSE                  61372
#define IDS_ZIP_EXISTDLG                61373
#define IDS_FILE_EXISTDLG               61373
#define IDS_PRJ_ERR_BASELEN             61374
#define IDS_PRJ_LONGNOTIFY              61375
#define IDS_PRJ_ERR_PRJEXT              61376
#define IDS_PRJ_NOTSURVEY               61377
#define IDS_PRJ_ERR_BASEEXT             61378
#define IDS_ERR_GPSTIME1                61379
#define IDS_GPS_PARTIALOK               61380
#define IDS_ERR_GPSABORT1               61381
#define IDS_GPS_PRJPATH                 61382
#define IDS_GPS_OVERWRITE               61383
#define IDS_ERR_NOGPSPATH               61384
#define IDS_ERR_BADPATH                 61385
#define IDS_GPS_OVERWRITE1              61386
#define IDS_GPS_PRJOPEN                 61387
#define IDS_ERR_LAUNCH_FNF              61388
#define IDS_ERR_LAUNCH_ASSOC            61389
#define IDS_ERR_LAUNCH                  61390
#define IDS_ERR_SRVSAVEAS               61391
#define IDS_SRV_FILESAVEAS              61392
#define IDS_PRJ_SAVEASLEAF              61393
#define IDS_ERR_SVG_ADJUST              61394
#define IDS_SVG_NONMERGED2              61395
#define IDS_ERR_WPTNAME                 61396
#define IDS_ERR_BADRENAME1              61397
#define IDS_PRJ_SRVRENAME1              61398
#define IDS_ERR_SURVOPEN1               61399
#define IDS_PRJ_DELETEORG1              61400
#define IDS_SVG_STATUS                  61401
#define IDS_LRUD_DLGTITLE               61402
#define IDS_ERR_NOTSTANAME              61403
#define IDS_ERR_NEEDNAMEPAIR            61404
#define IDS_ERR_VECNOFINDEDIT           61405
#define IDS_ERR_NAMEPFX                 61406
#define IDS_ERR_MULTIPLEMATCH           61407
#define IDS_ERR_FIXDUPLICATE            61408
#define IDS_ERR_VALUERANGE2             61409
#define IDS_ERR_VALUELIMIT              61410
#define IDS_SVG_BIGLABELS1              61411
#define IDS_SVG_UNAVAILABLE             61412
#define IDS_ERR_REGEXNOFIND             61413
#define IDS_TAB_NOTE                    61414
#define IDS_ERR_SEGOPEN1                61415
#define IDS_PRJ_REPLWRAP1               61416
#define IDS_ERR_NETLIB                  61417
#define IDC_TIPFRAME                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         33020
#define _APS_NEXT_CONTROL_VALUE         672
#define _APS_NEXT_SYMED_VALUE           149
#endif
#endif
