// version.h
#pragma once

#define STRINGIFY_HELPER(x)		#x
#define STRINGIFY(x)			STRINGIFY_HELPER(x)

#ifndef WALLS_VER_MAJOR
#define WALLS_VER_MAJOR				2
#endif
#ifndef WALLS_VER_MINOR
#define WALLS_VER_MINOR				2
#endif
#ifndef WALLS_VER_PATCH
#define WALLS_VER_PATCH				1
#endif
#ifndef WALLS_VER_BUILD
#define WALLS_VER_BUILD				0
#endif

#ifndef WALLS_BUILD_DATE
#define WALLS_BUILD_DATE				"2026-06-15"
#endif

#define WALLS_VERSION					STRINGIFY(WALLS_VER_MAJOR) "." STRINGIFY(WALLS_VER_MINOR) "." STRINGIFY(WALLS_VER_PATCH) "." STRINGIFY(WALLS_VER_BUILD)

