#pragma once

/*Error codes used by WALLS. WALL-SRV.DLL must use different return codes
for its internal messages --*/
#define SRV_ERR_EOF		  -1
#define SRV_ERR_DUPNAMES  -2
#define SRV_ERR_DISPLAYED -3
#define SRV_ERR_MAGDLL  -4

/*Error codes returned by srv_Next() but set in srv_CB() in COMPILE.CPP --*/
enum {
	SRV_ERR_BADFLAGNAME=1,
	SRV_ERR_NOFLAGNAME,
	SRV_ERR_LOCAL
};

//wall_emsg.h -- used by wall-exp.cpp (wallexp.dll), expsef.cpp and wall-srv.cpp (walls32.exe)
enum {
	SRV_ERR_OPEN=SRV_ERR_LOCAL, //in wall_srv.h
	SRV_ERR_REOPEN,
	SRV_ERR_SIZNAME,
	SRV_ERR_LINLEN,
	SRV_ERR_NUMARGS,
	SRV_ERR_DECLINATION,
	SRV_ERR_CORRECTION,   //==10
	SRV_ERR_SPECIFIER,
	SRV_ERR_ANGLEUNITS,
	SRV_ERR_ORDER,
	SRV_ERR_AZIMUTH,
	SRV_ERR_DISTANCE,
	SRV_ERR_VERTICAL,
	SRV_ERR_NUMERIC,
	SRV_ERR_VARIANCE,
	SRV_ERR_UNEXPVALUE,
	SRV_ERR_SEGPATH,		//==20
	SRV_ERR_SEGSIZE,
	SRV_ERR_DIRECTIVE,
	SRV_ERR_LINECMD,
	SRV_ERR_UV,
	SRV_ERR_PREFIX,
	SRV_ERR_NOPAREN,
	SRV_ERR_BADSYMBOL,
	SRV_ERR_NONAMEPFX,
	SRV_ERR_CMDBLANK,
	SRV_ERR_NOPARAM,		//==30
	SRV_ERR_SLASH,
	SRV_ERR_BACKDELTA,
	SRV_ERR_TAPEMETH,
	SRV_ERR_NOTEARG,
	SRV_ERR_COMMOPEN,
	SRV_ERR_COMMCLOSE,
	SRV_ERR_DATE,
	SRV_ERR_RESTORE,
	SRV_ERR_SAVE,
	SRV_ERR_SIGNREV,		//==40
	SRV_ERR_EQUALS,
	SRV_ERR_LENUNITS,
	SRV_ERR_BADANGLE,
	SRV_ERR_BADLENGTH,
	SRV_ERR_BLANK,
	SRV_ERR_AZIMUTHSIGN,
	SRV_ERR_TYPEBACK,
	SRV_ERR_FSBSERR,
	SRV_ERR_LRUDARGS,
	SRV_ERR_LRUDMETH,	//==50
	SRV_ERR_LATLONG,
	SRV_ERR_NODATUM,
	SRV_ERR_BADCOLOR,
	SRV_ERR_SPRAYNAME,
	SRV_ERR_MACRONOVAL,
	SRV_ERR_MACRONODEF,
	SRV_ERR_NOMEM,
	SRV_ERR_LENPREFIX,
	SRV_ERR_COMPPREFIX,
	SRV_ERR_CHRPREFIX,  //==60
	SRV_ERR_IT_HEIGHTS,
	SRV_ERR_HZ_LENGTH,
	SRV_ERR_REL_DEPTH,
	SRV_ERR_SEGNAMLEN,
	SRV_ERR_UNITSDATE,
	SRV_ERR_ERRLIM
};
//used only for SEF export
enum {
	EXP_ERR_INITSEF=SRV_ERR_ERRLIM,
	EXP_ERR_LENGTH,
	EXP_ERR_VERSION
};

#define EXP_ERR_SETOPTIONS -1
#define EXP_ERR_DATEDECL -2
#define EXP_ERR_LOADDECL -3
#define EXP_ERR_CLOSE -4

#define SS_ERR_IGNORE (0.1+FLT_EPSILON)
#define SS_ERR_FATAL (10+FLT_EPSILON)
